# Form implementation generated from reading ui file 'studentpreformance.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
# Importing the QTableWidgetItem from QtWidgets.
from PyQt6.QtWidgets import QTableWidgetItem
# importing the pymysql package and calling it with an alias mdb
import pymysql as mdb



class Ui_studentPreformance(object):
    def setupUi(self, studentPreformance):
        studentPreformance.setObjectName("studentPreformance")
        studentPreformance.resize(1125, 860)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        studentPreformance.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=studentPreformance)
        self.centralwidget.setObjectName("centralwidget")
        self.lbId = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbId.setGeometry(QtCore.QRect(280, 90, 111, 16))
        self.lbId.setObjectName("lbId")
        self.txtId = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtId.setGeometry(QtCore.QRect(430, 90, 113, 22))
        self.txtId.setObjectName("txtId")
        self.lblName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblName.setGeometry(QtCore.QRect(260, 140, 141, 20))
        self.lblName.setObjectName("lblName")
        self.txtName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtName.setGeometry(QtCore.QRect(430, 140, 113, 22))
        self.txtName.setObjectName("txtName")
        self.lnlScore = QtWidgets.QLabel(parent=self.centralwidget)
        self.lnlScore.setGeometry(QtCore.QRect(260, 190, 131, 20))
        self.lnlScore.setObjectName("lnlScore")
        self.txtScore = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtScore.setGeometry(QtCore.QRect(430, 190, 113, 22))
        self.txtScore.setObjectName("txtScore")
        self.btnInsert = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnInsert.setGeometry(QtCore.QRect(280, 260, 93, 28))
        self.btnInsert.setObjectName("btnInsert")
        self.btnDisplay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDisplay.setGeometry(QtCore.QRect(440, 260, 93, 28))
        self.btnDisplay.setObjectName("btnDisplay")
        self.studentTableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.studentTableWidget.setGeometry(QtCore.QRect(245, 340, 331, 192))
        self.studentTableWidget.setObjectName("studentTableWidget")
        self.studentTableWidget.setColumnCount(0)
        self.studentTableWidget.setRowCount(0)
        studentPreformance.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=studentPreformance)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 26))
        self.menubar.setObjectName("menubar")
        studentPreformance.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=studentPreformance)
        self.statusbar.setObjectName("statusbar")
        studentPreformance.setStatusBar(self.statusbar)

        self.retranslateUi(studentPreformance)
        QtCore.QMetaObject.connectSlotsByName(studentPreformance)
        
        # Define the connection to open the database.
        self.connection = self.createdbconnection()
        # If the connetion was successful, call the add_data() method
        if self.connection:
            self.add_data("studentdata.txt")
        
        # Define the functions to execute when clicking the Insert Data and Display Data buttons.
        self.btnInsert.clicked.connect(self.insert_data)
        self.btnDisplay.clicked.connect(self.display_data)

    def retranslateUi(self, studentPreformance):
        _translate = QtCore.QCoreApplication.translate
        studentPreformance.setWindowTitle(_translate("studentPreformance", "Student Preformance"))
        self.lbId.setText(_translate("studentPreformance", "Enter Student ID"))
        self.lblName.setText(_translate("studentPreformance", "Enter Student Name"))
        self.lnlScore.setText(_translate("studentPreformance", "Enter Student Score"))
        self.btnInsert.setText(_translate("studentPreformance", "Insert Data"))
        self.btnDisplay.setText(_translate("studentPreformance", "Display Data"))
    
    # Define the createdbconnection function to open a connection to the studentpreformance database.
    def createdbconnection(self):
        try:
            # Create a connection object to open a connection to the studentpreformance database.
            connectionobj = mdb.connect(host="localhost", user="studentuser", password="studentuser", database="studentpreformancedb")
            # Print a message to indicate the database connection was successful.
            print("Connected to DB")
            return connectionobj
        
        # Generic exception block for all other unexpected errors.
        except Exception as e:
            # Print an error message to indicate there was an error connecting to the database.
            print("Error connecting to DB")
            print(e)
            return None
    
    # Define the delete_data function to remove rows from the studentpreformance table of the database.
    def delete_data(self, studentid):
        try:
            cursor = self.connection.cursor()
            cursor.execute("delete from studentpreformance where studentid = %s", [studentid])
            self.connection.commit()
        
        # Generic exception block for all other unexpected errors.
        except Exception as e:
            print(e)
    
        # Close the cursor object that was created above.
        finally:
            cursor.close()
        
    # Define the insert_data function to insert the student ID, name, and score entered by the user into the studentpreformance table in the database.
    def insert_data(self):
        try:
            # Get the user's student ID and store it in the student_id variable.
            student_id = self.txtId.text()
            # Get the user's student_name and store it in the student_name variable.
            student_name = self.txtName.text()
            # Get the user's student_score and store it in the student_score variable.
            student_score = self.txtScore.text()
            
            #Create a cursor object
            cursor = self.connection.cursor()
                
            # Validate the user has entered the Name as letters and has entered the ID and Score as numbers.
            if(student_name.replace(" ","").isalpha() and student_id.isdigit() and student_score.isdigit()):
                # Insert the user inputs into the studentpreformance table.
                cursor.execute("insert into studentpreformance (studentid, studentname, studentscore)values(%s,%s,%s)",[student_id,student_name,student_score])
                self.connection.commit()
                # Print a message to indicate successful addition of data.
                print("added data to the table")
                
                # Clear the text boxes
                self.txtId.clear()
                self.txtName.clear()
                self.txtScore.clear()
        
            else:
                # Display an error message to the user if the Name, ID, and Score are not filled in correctly.
                msg = QtWidgets.QMessageBox()
                # Set the title of the Message Box to Student Performance.
                msg.setWindowTitle("Student Performance")
                # Set the display text of the Message Box.
                msg.setText("Please enter valid inputs for the ID, Name, and Score")
                # Execute the Message Box.
                msg.exec()
        
        # Generic exception block for all other unexpected errors.
        except Exception as e:    
            # Print an error message indicating there was an error adding the data.
            print("Error inserting data")
            print(e)
        
        # Close the cursor object that was created above.
        finally:
            cursor.close()
    
    # Define the add_data function to read data from an external file called studentdata.txt into the studentpreformance table of the database.
    def add_data(self, file_name):
        try:
            # Create a cursor object.
            cursor = self.connection.cursor()
            # Read each line of the studentdata.txt file and insert it into the studentpreformance table.
            with open(file_name, 'r') as fname:
                for line in fname:
                    # trim(): C#
                    # strip() remove whitespaces in the data
                    data_lst = line.strip().split(",")
                    # [107, 'Steve Sides, 89]
                    # Insert the line of the studentdata.txt file into the studentpreformance table.
                    cursor.execute("insert into studentpreformance (studentid, studentname, studentscore) values (%s,%s,%s)",[data_lst[0].strip(), data_lst[1].strip(), data_lst[2].strip()])
                    self.connection.commit()
                    # Print a message to indicate that the line of the studentdata.txt file was added to the studentpreformance table.
                    print("Added data to the table")
        
        # Generic exception block for all other unexpected errors.
        except Exception as e:
            # Print an error message indicating there was an error adding the data.
            print("There was an error adding data")
            print(e)
        
        # Close the cursor object that was created above.
        finally:
            cursor.close()
    
    # Define the display_data function to display all rows of the studentpreformance table of the database in the Table Widget object.
    def display_data(self):
        try:
            # Create a cursor object.
            cursor = self.connection.cursor()
            # Select all records in the studentpreformance table.
            cursor.execute("select * from studentpreformance")
            results = cursor.fetchall()
            #finding number of rows
            row_count = len(results)
            # finding number of columns
            column_count = len(cursor.description)
            #print(results)
            #print(cursor.description)
            # set row count
            self.studentTableWidget.setRowCount(row_count)
            #set column count
            self.studentTableWidget.setColumnCount(column_count)
            # Add column headers
            column_name_lst = ['Id', 'Name', 'Performance']
            #Set the column headers for the tableWidget
            self.studentTableWidget.setHorizontalHeaderLabels(column_name_lst)
            
            # enumerate(results) helps access the row number and the row data
            # enumerate(results) helps access the column number and the column data within each row.
            #rowindex and columnindex start at 0
            for rowindex, rowdata in enumerate(results):
                for columnindex, data in enumerate(rowdata):
                    if columnindex == 2:
                        performance = self.get_performance(data)
                        self.studentTableWidget.setItem(rowindex, columnindex, QTableWidgetItem(performance))
                    else:
                        self.studentTableWidget.setItem(rowindex, columnindex, QTableWidgetItem(str(data)))
        
        # Generic exception block for all other unexpected errors.        
        except Exception as e:
            print(e)
        
        # Close the cursor object that was created above.
        finally:
            cursor.close()
            
    # Define the get_performance funtion to determine if the score is Good or Not Good.
    def get_performance(self, data):
        try:
            # If the score is above 80, the performance is Good.  Otherwise, the performance is Not Good.
            if data > 80:
                return "Good"
            else:
                return "Not Good"
            
        # Generic exception block for all other unexpected errors.        
        except Exception as e:
            print(e)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studentPreformance = QtWidgets.QMainWindow()
    ui = Ui_studentPreformance()
    ui.setupUi(studentPreformance)
    studentPreformance.show()
    sys.exit(app.exec())
