# Form implementation generated from reading ui file 'studentgrade.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
# Importing the QTableWidgetItem from QtWidgets.
from PyQt6.QtWidgets import QTableWidgetItem
# Importing the pymysql package and calling it with an alias mdb
import pymysql as mdb


class Ui_studentGrade(object):
    def setupUi(self, studentGrade):
        studentGrade.setObjectName("studentGrade")
        studentGrade.resize(1118, 853)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        studentGrade.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=studentGrade)
        self.centralwidget.setObjectName("centralwidget")
        self.tbStudentDetails = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tbStudentDetails.setGeometry(QtCore.QRect(10, 10, 1101, 761))
        self.tbStudentDetails.setObjectName("tbStudentDetails")
        self.tabStudentInfo = QtWidgets.QWidget()
        self.tabStudentInfo.setObjectName("tabStudentInfo")
        self.lblStudentId = QtWidgets.QLabel(parent=self.tabStudentInfo)
        self.lblStudentId.setGeometry(QtCore.QRect(350, 100, 111, 20))
        self.lblStudentId.setObjectName("lblStudentId")
        self.txtStudentId = QtWidgets.QLineEdit(parent=self.tabStudentInfo)
        self.txtStudentId.setGeometry(QtCore.QRect(560, 100, 161, 22))
        self.txtStudentId.setObjectName("txtStudentId")
        self.lblStudentName = QtWidgets.QLabel(parent=self.tabStudentInfo)
        self.lblStudentName.setGeometry(QtCore.QRect(350, 150, 141, 20))
        self.lblStudentName.setObjectName("lblStudentName")
        self.txtStudentName = QtWidgets.QLineEdit(parent=self.tabStudentInfo)
        self.txtStudentName.setGeometry(QtCore.QRect(560, 150, 161, 22))
        self.txtStudentName.setObjectName("txtStudentName")
        self.lblStudentScore = QtWidgets.QLabel(parent=self.tabStudentInfo)
        self.lblStudentScore.setGeometry(QtCore.QRect(350, 200, 141, 20))
        self.lblStudentScore.setObjectName("lblStudentScore")
        self.txtStudentScore = QtWidgets.QLineEdit(parent=self.tabStudentInfo)
        self.txtStudentScore.setGeometry(QtCore.QRect(560, 200, 161, 22))
        self.txtStudentScore.setObjectName("txtStudentScore")
        self.btnDisplayData = QtWidgets.QPushButton(parent=self.tabStudentInfo)
        self.btnDisplayData.setGeometry(QtCore.QRect(590, 270, 93, 28))
        self.btnDisplayData.setObjectName("btnDisplayData")
        self.btnInsertData = QtWidgets.QPushButton(parent=self.tabStudentInfo)
        self.btnInsertData.setGeometry(QtCore.QRect(380, 270, 93, 28))
        self.btnInsertData.setObjectName("btnInsertData")
        self.studentTableWidget = QtWidgets.QTableWidget(parent=self.tabStudentInfo)
        self.studentTableWidget.setGeometry(QtCore.QRect(350, 340, 371, 291))
        self.studentTableWidget.setObjectName("studentTableWidget")
        self.studentTableWidget.setColumnCount(0)
        self.studentTableWidget.setRowCount(0)
        self.tbStudentDetails.addTab(self.tabStudentInfo, "")
        self.tabStudentGrade = QtWidgets.QWidget()
        self.tabStudentGrade.setObjectName("tabStudentGrade")
        self.lstStudentGrades = QtWidgets.QListWidget(parent=self.tabStudentGrade)
        self.lstStudentGrades.setGeometry(QtCore.QRect(80, 60, 931, 331))
        self.lstStudentGrades.setObjectName("lstStudentGrades")
        self.btnExportData = QtWidgets.QPushButton(parent=self.tabStudentGrade)
        self.btnExportData.setGeometry(QtCore.QRect(490, 420, 93, 28))
        self.btnExportData.setObjectName("btnExportData")
        self.tbStudentDetails.addTab(self.tabStudentGrade, "")
        studentGrade.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=studentGrade)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1118, 26))
        self.menubar.setObjectName("menubar")
        studentGrade.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=studentGrade)
        self.statusbar.setObjectName("statusbar")
        studentGrade.setStatusBar(self.statusbar)

        self.retranslateUi(studentGrade)
        self.tbStudentDetails.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(studentGrade)
        
        # Define the connection to open the database. 
        self.connection = self.createdbconnection()
        # If the database connection was successful, call the add_data function.
        if self.connection:
            self.add_data("studentdata.txt")
        # Define the function that is executed when clicking the Insert Data, Display Data, and Export Data buttons.
        self.btnInsertData.clicked.connect(self.insert_data)
        self.btnDisplayData.clicked.connect(self.display_data)
        self.btnExportData.clicked.connect(self.export_data)
        # Define the function that is executed when clicking on the Student Grade tab.
        self.tbStudentDetails.currentChanged.connect(self.display_grade)

    def retranslateUi(self, studentGrade):
        _translate = QtCore.QCoreApplication.translate
        studentGrade.setWindowTitle(_translate("studentGrade", "Student Grade"))
        self.lblStudentId.setText(_translate("studentGrade", "Enter Student ID"))
        self.lblStudentName.setText(_translate("studentGrade", "Enter Student Name"))
        self.lblStudentScore.setText(_translate("studentGrade", "Enter Student Score"))
        self.btnDisplayData.setText(_translate("studentGrade", "Display Data"))
        self.btnInsertData.setText(_translate("studentGrade", "Insert Data"))
        self.tbStudentDetails.setTabText(self.tbStudentDetails.indexOf(self.tabStudentInfo), _translate("studentGrade", "Student Info"))
        self.btnExportData.setText(_translate("studentGrade", "Export Data"))
        self.tbStudentDetails.setTabText(self.tbStudentDetails.indexOf(self.tabStudentGrade), _translate("studentGrade", "Student Grade"))
    
    # Define the createdbconnection function to open a connection to the project4db database.
    def createdbconnection(self):
        try:
            # Create connectionobj object to open connection to the project4db database.
            connectionobj = mdb.connect(host="localhost", user="studentuser", password="studentuser", database="project4db")
            # Print a message to indicate that database connection was successful. 
            print("Connected to DB")
            return connectionobj
        
        # Generic exception block for all other unexpected errors
        except Exception as e:
            # Print an error message to indicate there was an error connecting to the database.
            print("Error connecting to DB")
            print(e)
            return None

    # Define the add_data function to read the data from the external file called "studentdata.txt" into the studentgrade table of the project4db database.
    def add_data(self, file_name):
        try:
            # Create a cursor object.
            cursor = self.connection.cursor()
            # Read each line of the studentdata.txt file and insert into the studentgrade table.
            with open(file_name, 'r') as fname:
                for line in fname:
                    # strip() will remove extra whitespaces before and after the text.
                    # split() will split the data based on the delimiter of ",".
                    data_lst = line.strip().split(",")
                    # Insert the line of the studentdata.txt file into the studentgrade table.
                    cursor.execute("insert into studentgrade (studentid, studentname, studentscore) values (%s, %s, %s)", [data_lst[0].strip(), data_lst[1].strip(), data_lst[2].strip()])
                    self.connection.commit()
                    # Print a message to indicate that the line of the studentdata.txt file was added to the studentgrade table.
                    print("Added data to the table from the external file")
        
        # Specific exception block to handle file not found error.
        except FileNotFoundError:
            print("External file does not exist")
        
        # Generic exception block for all other unexpected errors        
        except Exception as e:
            # Print a message to indicate there was an error adding the line of the studentdata.txt file to the studentgrade table.
            print("There was an error adding data from the external file")
            print(e) 

        # Close the cursor object that was created above.
        finally:
            cursor.close()
    
    # Define the insert_data function to read all user inputs and insert them into the studentgrade table of the project4db database.
    def insert_data(self):
        try:
            # Get the Student ID and store it in the student_id variable.
            student_id = self.txtStudentId.text()
            # Get the Student Name and store it in the student_name variable.
            student_name = self.txtStudentName.text()
            # Get the Student Score and store it in the student_score variable.
            student_score = self.txtStudentScore.text()
            
            # Create a cursor object
            cursor = self.connection.cursor()
                
            # Validate the user has entered the Name as letters and has entered the ID and Score as numbers.
            if(student_name.replace(" ","").isalpha() and student_id.isdigit() and student_score.isdigit()):
            
                # Insert the user inputs into the studentgrade table of the project4db database.
                cursor.execute("insert into studentgrade (studentid, studentname, studentscore) values (%s,%s,%s)",[student_id, student_name, student_score])
                self.connection.commit()
                # Print a message to indicate the data was successfully added to the studentgrade table.
                print("Added data to the table")
                # Display a message to indicate successful addition of data
                msg = QtWidgets.QMessageBox()
                # set the title of the message box to Student Grade
                msg.setWindowTitle("Student Grade")
                # set the display text of the message box
                msg.setText("Record successfully added.")
                # Execute the message box
                msg.exec()
            
                # Clear the text boxes
                # Clear the Student ID text box
                self.txtStudentId.clear()
                # Clear the Student Name text box
                self.txtStudentName.clear()
                # Clear the Student Score text box
                self.txtStudentScore.clear()
                
            else:
                # Display an error message to the user if the Name, ID, and Score are not filled in.
                msg = QtWidgets.QMessageBox()
                # Set the title of the Message Box to Student Grade.
                msg.setWindowTitle("Student Grade")
                # Set the display text of the Message Box.
                msg.setText("Please enter valid inputs for the Name, ID, and Score.")
                # Execute the Message Box
                msg.exec()    
        
        # Generic exception block for all other unexpected errors        
        except Exception as e:
            # Print an error message to indicate the data was not successfully added to the studentgrade table.
            print("Error inserting data")
            print(e)
            # Display a message to indicate there was an error adding the data
            msg = QtWidgets.QMessageBox()
            # set the title of the message box to Student Grade
            msg.setWindowTitle("Student Grade")
            # set the display text of the message box
            msg.setText("Error adding the data.")
            # Execute the message box
            msg.exec()
            
        # Close the cursor object that was created above.
        finally:
            cursor.close() 
  
    # Define the display_data function to display all rows of data in the studentgrade table of the project4db database in the Table Widget object on the
    # Student Info tab.
    def display_data(self):
        try:
            # Create a cursor object.
            cursor = self.connection.cursor()
            # Select all records in the studentgrade table.
            cursor.execute("select * from studentgrade")
            results = cursor.fetchall()
            # Find the number of rows in the studentgrade table.
            row_count = len(results)
            # Find the number of columns in the studentgrade table.
            column_count = len(cursor.description)
            # Print the rows in the studentgrade table.
            print(results)
            # Print the column information for the studentgrade table.
            print(cursor.description)
        
            # Set the row count for the studentTableWidget.
            self.studentTableWidget.setRowCount(row_count)
            # Set the column count for the studentTableWidget.
            self.studentTableWidget.setColumnCount(column_count)
            # Add the column headers to the studentTableWidget.
            column_name_lst = ['ID', 'Name', 'Score']
            # Set the column headers for the studentTableWidget.
            self.studentTableWidget.setHorizontalHeaderLabels(column_name_lst)
            
            # Use enumerate(results) to access the row number and the row data.
            for rowindex, rowdata in enumerate(results):
                # Use enumerate(results) to access the column number and the column data within each row.
                for columnindex, data in enumerate(rowdata):
                    # Display the data for each row and column index in the Table Widget.
                    self.studentTableWidget.setItem(rowindex, columnindex, QTableWidgetItem(str(data)))
        
        # Generic exception block for all other unexpected errors        
        except Exception as e:
            print(e)
            
        # Close the cursor object that was created above.
        finally:
            cursor.close()      
    
    # Define the display_grade function to read the data from the studentgrade table and display each line in the list box on the Student Grade tab.
    def display_grade(self, index):
        try:
            # Clear the data on the Student Grade tab when the user clicks on the tab.
            self.lstStudentGrades.clear()
            
            # Create a cursor object.
            cursor = self.connection.cursor()
            # Select all records in the studentgrade table.
            cursor.execute("select * from studentgrade")
            results = cursor.fetchall()
            # Find the number of rows in the studentgrade table.
            row_count = len(results)
            # Find the number of columns in the studentgrade table.
            column_count = len(cursor.description)
                              
            # Write column headings to the list box on the Student Grade tab.
            self.lstStudentGrades.addItem("ID                  Name                  Grade")
                
            # Read each row of the studentgrade table and display each row in the list box on the Student Grade tab. 
            for rowdata in results:
                # Call the get_grade function to calculate the letter grade based on the student score.
                student_grade = self.get_grade(rowdata[2])
                self.lstStudentGrades.addItem(str(rowdata[0])+"              "+str(rowdata[1])+"               "+str(student_grade))
            
        # Generic exception block for all other unexpected errors
        except Exception as e:
            print(e) 
    
        # Close the cursor object that was created above.
        finally:
            cursor.close()

    # Define the get_grade function to calculate the equivalent letter grade for the Student Score.
    def get_grade(self, data):
        try:
            # If the Student Score is less than 60, the grade is "F".
            if data < 60:
                return "F"
            # If the Student Score is between 60 and 69, the grade is "D".
            elif ((data >= 60) and (data <= 69)):
                return "D"
            # If the Student Score is between 70 and 79, the grade is "C".
            elif ((data >= 70) and (data <= 79)):
                return "C"
            # If the Student Score is between 80 and 89, the grade is "B".
            elif ((data >= 80) and (data <= 89)):
                return "B"
            # Otherwise, the grade is "A".
            else:
                return "A"
                
        # Generic exception block for all other unexpected errors        
        except Exception as e:
            print(e)
            
    # Define the export_data function to write the Student ID, Student Name, and Student Grade to an external file called studentgrades.txt.
    def export_data(self):
        try:
            # Create a cursor object.
            cursor = self.connection.cursor()
            # Select all records in the studentgrade table.
            cursor.execute("select * from studentgrade")
            results = cursor.fetchall()
            # Find the number of rows in the studentgrade table.
            row_count = len(results)
            # Find the number of columns in the studentgrade table.
            column_count = len(cursor.description)
                   
            # Use enumerate(results) to access the row number and the row data.
            for rowindex, rowdata in enumerate(results):
                # Use enumerate(results) to access the column number and the column data within each row.
                for columnindex, data in enumerate(rowdata):
                    # If the third column of the studentgrade table for the studentid, call the get_grade function to calculate the letter grade.
                    if columnindex == 2:
                        student_grade = self.get_grade(data)
                        # Once the letter grade is calculated, write the Student Grade to the external file.
                        with open("studentgrades.txt", "a") as fname:
                            fname.write(str(student_grade)+"\n")
                    # If the first or second column of the studentgrade table, write the data to the external file.    
                    else:
                        with open("studentgrades.txt", "a") as fname:
                            fname.write(str(data)+",  ")
                                    
                # Print a message to indicate that the row was successfully written to the external file.
                print("Row successfully written to the external file.")
       
        # Generic exception block for all other unexpected errors
        except Exception as e:
            print(e)

        # Close the cursor object that was created above.
        finally:
            cursor.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studentGrade = QtWidgets.QMainWindow()
    ui = Ui_studentGrade()
    ui.setupUi(studentGrade)
    studentGrade.show()
    sys.exit(app.exec())
