# Generated by Django 4.2 on 2025-04-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0002_enrollmentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentdetails',
            name='coursename',
        ),
    ]
