# Form implementation generated from reading ui file 'ticketpurchase.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ticketPurchase(object):
    def setupUi(self, ticketPurchase):
        ticketPurchase.setObjectName("ticketPurchase")
        ticketPurchase.resize(1105, 846)
        self.centralwidget = QtWidgets.QWidget(parent=ticketPurchase)
        self.centralwidget.setObjectName("centralwidget")
        self.tbTicketPurchase = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tbTicketPurchase.setGeometry(QtCore.QRect(0, 0, 1061, 751))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.tbTicketPurchase.setFont(font)
        self.tbTicketPurchase.setObjectName("tbTicketPurchase")
        self.tabTicketPurchase = QtWidgets.QWidget()
        self.tabTicketPurchase.setObjectName("tabTicketPurchase")
        self.btnClear = QtWidgets.QPushButton(parent=self.tabTicketPurchase)
        self.btnClear.setGeometry(QtCore.QRect(430, 390, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.txtTotalCost = QtWidgets.QLineEdit(parent=self.tabTicketPurchase)
        self.txtTotalCost.setGeometry(QtCore.QRect(270, 510, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtTotalCost.setFont(font)
        self.txtTotalCost.setObjectName("txtTotalCost")
        self.btnPurchase = QtWidgets.QPushButton(parent=self.tabTicketPurchase)
        self.btnPurchase.setGeometry(QtCore.QRect(290, 390, 111, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnPurchase.setFont(font)
        self.btnPurchase.setObjectName("btnPurchase")
        self.txtName = QtWidgets.QLineEdit(parent=self.tabTicketPurchase)
        self.txtName.setGeometry(QtCore.QRect(270, 110, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtName.setFont(font)
        self.txtName.setObjectName("txtName")
        self.btnExit = QtWidgets.QPushButton(parent=self.tabTicketPurchase)
        self.btnExit.setGeometry(QtCore.QRect(550, 390, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnExit.setFont(font)
        self.btnExit.setObjectName("btnExit")
        self.cmbSelection = QtWidgets.QComboBox(parent=self.tabTicketPurchase)
        self.cmbSelection.setGeometry(QtCore.QRect(270, 240, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.cmbSelection.setFont(font)
        self.cmbSelection.setObjectName("cmbSelection")
        self.cmbSelection.addItem("")
        self.cmbSelection.addItem("")
        self.cmbSelection.addItem("")
        self.grpNumberOfTickets = QtWidgets.QGroupBox(parent=self.tabTicketPurchase)
        self.grpNumberOfTickets.setGeometry(QtCore.QRect(500, 250, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.grpNumberOfTickets.setFont(font)
        self.grpNumberOfTickets.setObjectName("grpNumberOfTickets")
        self.rd1 = QtWidgets.QRadioButton(parent=self.grpNumberOfTickets)
        self.rd1.setGeometry(QtCore.QRect(10, 20, 41, 20))
        self.rd1.setObjectName("rd1")
        self.rd2 = QtWidgets.QRadioButton(parent=self.grpNumberOfTickets)
        self.rd2.setGeometry(QtCore.QRect(80, 20, 41, 20))
        self.rd2.setObjectName("rd2")
        self.rd3 = QtWidgets.QRadioButton(parent=self.grpNumberOfTickets)
        self.rd3.setGeometry(QtCore.QRect(150, 20, 41, 20))
        self.rd3.setObjectName("rd3")
        self.lblAge = QtWidgets.QLabel(parent=self.tabTicketPurchase)
        self.lblAge.setGeometry(QtCore.QRect(130, 160, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblAge.setFont(font)
        self.lblAge.setObjectName("lblAge")
        self.lblSelection = QtWidgets.QLabel(parent=self.tabTicketPurchase)
        self.lblSelection.setGeometry(QtCore.QRect(130, 220, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblSelection.setFont(font)
        self.lblSelection.setObjectName("lblSelection")
        self.btnCost = QtWidgets.QPushButton(parent=self.tabTicketPurchase)
        self.btnCost.setGeometry(QtCore.QRect(160, 390, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnCost.setFont(font)
        self.btnCost.setObjectName("btnCost")
        self.lblName = QtWidgets.QLabel(parent=self.tabTicketPurchase)
        self.lblName.setGeometry(QtCore.QRect(130, 90, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblName.setFont(font)
        self.lblName.setObjectName("lblName")
        self.txtAge = QtWidgets.QLineEdit(parent=self.tabTicketPurchase)
        self.txtAge.setGeometry(QtCore.QRect(270, 180, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtAge.setFont(font)
        self.txtAge.setObjectName("txtAge")
        self.lblCost = QtWidgets.QLabel(parent=self.tabTicketPurchase)
        self.lblCost.setGeometry(QtCore.QRect(140, 490, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblCost.setFont(font)
        self.lblCost.setObjectName("lblCost")
        self.tbTicketPurchase.addTab(self.tabTicketPurchase, "")
        self.tabPurchasesMade = QtWidgets.QWidget()
        self.tabPurchasesMade.setObjectName("tabPurchasesMade")
        self.lstPurchases = QtWidgets.QListWidget(parent=self.tabPurchasesMade)
        self.lstPurchases.setGeometry(QtCore.QRect(20, 70, 1041, 341))
        self.lstPurchases.setObjectName("lstPurchases")
        self.tbTicketPurchase.addTab(self.tabPurchasesMade, "")
        ticketPurchase.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ticketPurchase)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1105, 26))
        self.menubar.setObjectName("menubar")
        ticketPurchase.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ticketPurchase)
        self.statusbar.setObjectName("statusbar")
        ticketPurchase.setStatusBar(self.statusbar)

        self.retranslateUi(ticketPurchase)
        self.tbTicketPurchase.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ticketPurchase)
        
        # Create a new dictionary called price_dictionary that will be populated using the load_data function.
        self.price_dictionary = self.load_data("price.txt")
        # Define the functions that will be called when clicking on the Show Cost, Purchase, Clear, and Exit buttons.
        self.btnCost.clicked.connect(self.calculate_cost)
        self.btnPurchase.clicked.connect(self.purchases_made)
        self.btnClear.clicked.connect(self.clear)
        self.btnExit.clicked.connect(self.exit_application)
        # Define the function that is executed when clickin on the Purchases Made tab.
        self.tbTicketPurchase.currentChanged.connect(self.display_data)
        
    def retranslateUi(self, ticketPurchase):
        _translate = QtCore.QCoreApplication.translate
        ticketPurchase.setWindowTitle(_translate("ticketPurchase", "Ticket Purchase"))
        self.btnClear.setText(_translate("ticketPurchase", "Clear"))
        self.btnPurchase.setText(_translate("ticketPurchase", "Purchase"))
        self.btnExit.setText(_translate("ticketPurchase", "Exit"))
        self.cmbSelection.setItemText(0, _translate("ticketPurchase", "Toplevel"))
        self.cmbSelection.setItemText(1, _translate("ticketPurchase", "Midlevel"))
        self.cmbSelection.setItemText(2, _translate("ticketPurchase", "Courtside"))
        self.grpNumberOfTickets.setTitle(_translate("ticketPurchase", "Select Number of Tickets"))
        self.rd1.setText(_translate("ticketPurchase", "1"))
        self.rd2.setText(_translate("ticketPurchase", "2"))
        self.rd3.setText(_translate("ticketPurchase", "3"))
        self.lblAge.setText(_translate("ticketPurchase", "Enter Age"))
        self.lblSelection.setText(_translate("ticketPurchase", "Select Seat Type"))
        self.btnCost.setText(_translate("ticketPurchase", "Show Cost"))
        self.lblName.setText(_translate("ticketPurchase", "Enter Name"))
        self.lblCost.setText(_translate("ticketPurchase", "Total Cost"))
        self.tbTicketPurchase.setTabText(self.tbTicketPurchase.indexOf(self.tabTicketPurchase), _translate("ticketPurchase", "Ticket Purchase"))
        self.tbTicketPurchase.setTabText(self.tbTicketPurchase.indexOf(self.tabPurchasesMade), _translate("ticketPurchase", "Purchases Made"))
    
    # Define the load_data function to read each line of the price.txt file and load into a dictionary called price.
    def load_data(self, file_name):
        try:
            # creating an empty price dictionary
            price = {}
            # Read each line of the price.txt file.
            with open(file_name, "r") as fname:
                for line in fname:
                    seat_type, price_of_ticket = line.strip().split(",")
                    # Add a new key value pair to the dictionary.
                    price[seat_type] = int(price_of_ticket)
            return price
        
        # Specific exception block to handle file not found error    
        except FileNotFoundError:
            print("The file does not exist")
        
        # Generic exception block for all other unexpected errors   
        except Exception as e:
            print(e)  
    
    # Define the calculate_cost function to get the user's seat selection and number of tickets and display the purchase cost.
    def calculate_cost(self):
        try:
            # Get the user's selection of the number of tickets the user wants to buy and store it in the number_of_tickets variable.
            current_selection = self.cmbSelection.currentText()
            if(self.rd1.isChecked()):
                number_of_tickets = 1
            elif(self.rd2.isChecked()):
                number_of_tickets = 2
            elif(self.rd3.isChecked()):
                number_of_tickets = 3
            else:
                number_of_tickets = 0
            
            # get price of seat type using the dictionary get method/function and store it in the price_of_ticket variable.         
            price_of_ticket = self.price_dictionary.get(current_selection)
            
            # Calculate the total_cost variable based on the ticket price and number of tickets.
            total_cost = price_of_ticket * number_of_tickets
            # Display the Total Cost in the text box.
            self.txtTotalCost.setText("$"+str(total_cost))
        
        # Generic exception block for all other unexpected errors   
        except Exception as e:
            print(e)
    
    # Define the purchases_made function to accept all user inputs and write the data to an external file called purchases_made.txt.
    def purchases_made(self):
        try:
            # Get the user's name and store it in the name variable.
            name = self.txtName.text()
            # Get the user's age and store it in the age variable.
            age = self.txtAge.text()
            # Get the customer's seat selection and store it in the current_selection variable.
            current_selection = self.cmbSelection.currentText()
            
            # Get the user's seletion of the number of tickets the user wants to purchase and store it in the number_of_tickets variable.
            if(self.rd1.isChecked()):
                number_of_tickets = 1
            elif(self.rd2.isChecked()):
                number_of_tickets = 2
            elif(self.rd3.isChecked()):
                number_of_tickets = 3
            else:
                number_of_tickets = 0
            
            # "\n" to write each purchase to a new line
            # Write the user inputs and purchase to a new line in the purchases_made.txt file.
            with open("purchases_made.txt", "a") as fname:
                fname.write(name+",  "+age+",  "+current_selection+",  "+ str(number_of_tickets) + "\n")
        
        # Generic exception block for all other unexpected errors
        except Exception as e:
            print(e)
    
    # Define the clear function that resets all fields to their default values when the Clear button is clicked.
    def clear(self):
        try:
            # Clears the Name text box.
            self.txtName.clear()
            # Clears the Age text box.
            self.txtAge.clear()
            # Re-set the Seat Selection combo box to Toplevel.
            self.cmbSelection.setCurrentIndex(0)
            # Re-set the Number of Tickets radio button to 1.
            self.rd1.setChecked(True)
            # Clears the Total Cost text box.
            self.txtTotalCost.clear()
        
        # Generic exception block for all other unexpected errors   
        except Exception as e:
            print(e)
    
    # Define the display_data function to reac the purchases_made.txt file and display each line in the list box on the Purchases Made tab.
    def display_data(self, index):
        try:
            # Clear the data on the Purchases Made tab if the user clicks on the Ticket purchase tab.
            if(index == 0):
                self.lstPurchases.clear()
            # Read each line of the purchases_made.txt file and display each line in the list box.
            else:    
                with open("purchases_made.txt", "r") as fname:
                    for line in fname:
                        self.lstPurchases.addItem(line)
        
        # Specific exception block to handle file not found error    
        except FileNotFoundError:
            print("no purchase data exists")
        
        # Generic exception block for all other unexpected errors
        except Exception as e:
            print(e)

    # Define the exit_application function that closes the application when the Exit button is clicked.
    def exit_application(self):
        #Close the application when the Exit button is clicked.
        QtWidgets.QApplication.quit()        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ticketPurchase = QtWidgets.QMainWindow()
    ui = Ui_ticketPurchase()
    ui.setupUi(ticketPurchase)
    ticketPurchase.show()
    sys.exit(app.exec())
