# Form implementation generated from reading ui file 'studentscores.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_studentScores(object):
    def setupUi(self, studentScores):
        studentScores.setObjectName("studentScores")
        studentScores.resize(1120, 856)
        self.centralwidget = QtWidgets.QWidget(parent=studentScores)
        self.centralwidget.setObjectName("centralwidget")
        self.lblStudentScores = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblStudentScores.setGeometry(QtCore.QRect(350, 90, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblStudentScores.setFont(font)
        self.lblStudentScores.setObjectName("lblStudentScores")
        self.lstStudentScores = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lstStudentScores.setGeometry(QtCore.QRect(280, 140, 256, 261))
        self.lstStudentScores.setObjectName("lstStudentScores")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(330, 460, 161, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnCalculate.setFont(font)
        self.btnCalculate.setObjectName("btnCalculate")
        self.lblAverage = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAverage.setGeometry(QtCore.QRect(250, 520, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblAverage.setFont(font)
        self.lblAverage.setObjectName("lblAverage")
        self.txtAverage = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtAverage.setGeometry(QtCore.QRect(440, 530, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtAverage.setFont(font)
        self.txtAverage.setReadOnly(True)
        self.txtAverage.setObjectName("txtAverage")
        studentScores.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=studentScores)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 26))
        self.menubar.setObjectName("menubar")
        studentScores.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=studentScores)
        self.statusbar.setObjectName("statusbar")
        studentScores.setStatusBar(self.statusbar)

        self.retranslateUi(studentScores)
        QtCore.QMetaObject.connectSlotsByName(studentScores)
        
        # Create a new dictionary called student_scores_dictionary that will be populated using the load_data function.
        self.student_scores_dictionary = self.load_data("student_scores.txt")
        # Define the function that will be executed when clicking on the Calculate Average button.
        self.btnCalculate.clicked.connect(self.calculate_average)

    def retranslateUi(self, studentScores):
        _translate = QtCore.QCoreApplication.translate
        studentScores.setWindowTitle(_translate("studentScores", "Student Scores"))
        self.lblStudentScores.setText(_translate("studentScores", "Student Scores"))
        self.btnCalculate.setText(_translate("studentScores", "Calculate Average"))
        self.lblAverage.setText(_translate("studentScores", "Average Score"))
        
    # Define the load_data function to read each line of the student_scores.txt file and load into a dictionary called scores.    
    def load_data(self, file_name):
        # Creat an empty dictionary named scores
        scores = {}
        with open(file_name, "r") as fname:
            for line in fname:
                # strip() will remove extra white spaces before and after the text. split() will split based on the delimiter
                name, score = line.strip().split(",")
                # Add a new key value pair to the dictionary
                scores[name] = int(score)
                # Write the name and score to the list box
                self.lstStudentScores.addItem(str(name)+"     "+str(score))
        return scores  
     
    # Define the calculate_average function to calculate the average of the student scores from the student_scores.txt file.
    def calculate_average(self):
        total = 0
        # Define the length variable based on the number of key,value pairs in the student_scores_dictionary.
        length = len(self.student_scores_dictionary)
        # Calculate the average student score.
        for key,value in self.student_scores_dictionary.items():
            total = total + value
            
            average = total/length
            self.txtAverage.setText(str(average))   


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studentScores = QtWidgets.QMainWindow()
    ui = Ui_studentScores()
    ui.setupUi(studentScores)
    studentScores.show()
    sys.exit(app.exec())
