# Form implementation generated from reading ui file 'icecreamtruck.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_IceCreamTruck(object):
    def setupUi(self, IceCreamTruck):
        IceCreamTruck.setObjectName("IceCreamTruck")
        IceCreamTruck.resize(1121, 852)
        self.centralwidget = QtWidgets.QWidget(parent=IceCreamTruck)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTruckName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTruckName.setGeometry(QtCore.QRect(340, 100, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.lblTruckName.setFont(font)
        self.lblTruckName.setObjectName("lblTruckName")
        self.lblNumberCones = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblNumberCones.setGeometry(QtCore.QRect(210, 200, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblNumberCones.setFont(font)
        self.lblNumberCones.setObjectName("lblNumberCones")
        self.lblNumberSandwiches = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblNumberSandwiches.setGeometry(QtCore.QRect(210, 270, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblNumberSandwiches.setFont(font)
        self.lblNumberSandwiches.setObjectName("lblNumberSandwiches")
        self.lblNumberSoftServes = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblNumberSoftServes.setGeometry(QtCore.QRect(210, 350, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblNumberSoftServes.setFont(font)
        self.lblNumberSoftServes.setObjectName("lblNumberSoftServes")
        self.txtNumberCones = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtNumberCones.setGeometry(QtCore.QRect(700, 210, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtNumberCones.setFont(font)
        self.txtNumberCones.setObjectName("txtNumberCones")
        self.txtNumberSandwiches = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtNumberSandwiches.setGeometry(QtCore.QRect(700, 280, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtNumberSandwiches.setFont(font)
        self.txtNumberSandwiches.setObjectName("txtNumberSandwiches")
        self.txtNumberSoftServes = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtNumberSoftServes.setGeometry(QtCore.QRect(700, 350, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtNumberSoftServes.setFont(font)
        self.txtNumberSoftServes.setObjectName("txtNumberSoftServes")
        self.btnCheckOut = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCheckOut.setGeometry(QtCore.QRect(490, 500, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnCheckOut.setFont(font)
        self.btnCheckOut.setObjectName("btnCheckOut")
        self.lblTotalAmount = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTotalAmount.setGeometry(QtCore.QRect(210, 600, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblTotalAmount.setFont(font)
        self.lblTotalAmount.setObjectName("lblTotalAmount")
        self.txtTotalAmount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTotalAmount.setGeometry(QtCore.QRect(700, 610, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtTotalAmount.setFont(font)
        self.txtTotalAmount.setObjectName("txtTotalAmount")
        IceCreamTruck.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=IceCreamTruck)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1121, 26))
        self.menubar.setObjectName("menubar")
        IceCreamTruck.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=IceCreamTruck)
        self.statusbar.setObjectName("statusbar")
        IceCreamTruck.setStatusBar(self.statusbar)

        self.retranslateUi(IceCreamTruck)
        QtCore.QMetaObject.connectSlotsByName(IceCreamTruck)

        # Call the display_total_amount function when the Check Out button is clicked.
        self.btnCheckOut.clicked.connect(self.display_total_amount)
        
    def retranslateUi(self, IceCreamTruck):
        _translate = QtCore.QCoreApplication.translate
        IceCreamTruck.setWindowTitle(_translate("IceCreamTruck", "Ice Cream Truck"))
        self.lblTruckName.setText(_translate("IceCreamTruck", "I Scream For Ice Cream"))
        self.lblNumberCones.setText(_translate("IceCreamTruck", "Number of Cones ($3.00 each)"))
        self.lblNumberSandwiches.setText(_translate("IceCreamTruck", "Number of Ice Cream Sandwiches ($4.00 each)"))
        self.lblNumberSoftServes.setText(_translate("IceCreamTruck", "Number of Soft Serves ($2.50 each)"))
        self.btnCheckOut.setText(_translate("IceCreamTruck", "Check Out"))
        self.lblTotalAmount.setText(_translate("IceCreamTruck", "Total Amount"))

    # Define the display_total_amount function to show the total amount when the Check Out button is clicked.
    def display_total_amount(self):
        # Get the number of cones the customer wants to buy and store this number in the number_cones variable.
        number_cones = self.txtNumberCones.text()
        # Get the number of ice cream sandwiches the customer wants to buy and store this number in the number_sandwiches variable.
        number_sandwiches = self.txtNumberSandwiches.text()
        # Get the number of soft serves the customer wants to buy and store this number in the number_soft_serves variable.
        number_soft_serves = self.txtNumberSoftServes.text()
        # Calculate the total amount due by multiplying the count of each item by the price of each item and store it in the total_amount variable.
        total_amount = (float(number_cones) * 3) + (float(number_sandwiches) * 4) + (float(number_soft_serves) * 2.5)
        # Set the text of the txtTotalAmount text box equal to the total_amount variable. Formatted the total amount as a currency value.
        self.txtTotalAmount.setText('${:,.2f}'.format(total_amount))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IceCreamTruck = QtWidgets.QMainWindow()
    ui = Ui_IceCreamTruck()
    ui.setupUi(IceCreamTruck)
    IceCreamTruck.show()
    sys.exit(app.exec())
