# Form implementation generated from reading ui file 'averagescores.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_calculateScore(object):
    def setupUi(self, calculateScore):
        calculateScore.setObjectName("calculateScore")
        calculateScore.resize(1113, 850)
        self.centralwidget = QtWidgets.QWidget(parent=calculateScore)
        self.centralwidget.setObjectName("centralwidget")
        self.lblScore = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblScore.setGeometry(QtCore.QRect(320, 180, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblScore.setFont(font)
        self.lblScore.setObjectName("lblScore")
        self.txtScore = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtScore.setGeometry(QtCore.QRect(620, 200, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtScore.setFont(font)
        self.txtScore.setObjectName("txtScore")
        self.btnAddScore = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAddScore.setGeometry(QtCore.QRect(630, 280, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnAddScore.setFont(font)
        self.btnAddScore.setObjectName("btnAddScore")
        self.btnAverage = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAverage.setGeometry(QtCore.QRect(630, 340, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnAverage.setFont(font)
        self.btnAverage.setObjectName("btnAverage")
        self.btClear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btClear.setGeometry(QtCore.QRect(630, 450, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btClear.setFont(font)
        self.btClear.setObjectName("btClear")
        self.lstScores = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lstScores.setGeometry(QtCore.QRect(820, 190, 256, 361))
        self.lstScores.setObjectName("lstScores")
        self.lblStudentScores = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblStudentScores.setGeometry(QtCore.QRect(900, 130, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblStudentScores.setFont(font)
        self.lblStudentScores.setObjectName("lblStudentScores")
        calculateScore.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=calculateScore)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1113, 26))
        self.menubar.setObjectName("menubar")
        calculateScore.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=calculateScore)
        self.statusbar.setObjectName("statusbar")
        calculateScore.setStatusBar(self.statusbar)

        self.retranslateUi(calculateScore)
        QtCore.QMetaObject.connectSlotsByName(calculateScore)
        
        # Create an empty list to store each student score 
        self.student_scores_lst = []
        # Define the function that is executed when clicking the Add, Average, and Clear buttons.
        self.btnAddScore.clicked.connect(self.add_score)
        self.btnAverage.clicked.connect(self.calculate_average)
        self.btClear.clicked.connect(self.clear)

    def retranslateUi(self, calculateScore):
        _translate = QtCore.QCoreApplication.translate
        calculateScore.setWindowTitle(_translate("calculateScore", "Calculate Score"))
        self.lblScore.setText(_translate("calculateScore", "Enter Student Score"))
        self.btnAddScore.setText(_translate("calculateScore", "Add Score"))
        self.btnAverage.setText(_translate("calculateScore", "Average"))
        self.btClear.setText(_translate("calculateScore", "Clear"))
        self.lblStudentScores.setText(_translate("calculateScore", "Student Score"))
        
    # Define a function called add_score that accepts a student score from the user and adds it to the Scores list widget.    
    def add_score(self):
        if(self.txtScore.text().isnumeric()):
            # Convert the string input to a float
            student_score = float(self.txtScore.text())
            # append the new score to the list
            self.student_scores_lst.append(student_score)
            # Add the score to the list widget
            self.lstScores.addItem(str(student_score))
            
            self.txtScore.clear()
            self.txtScore.setFocus()
        else:
            # Create a new message box to indicate that the user entered an invalid score.
            msg = QtWidgets.QMessageBox()
            msg.setWindowTitle("Average Scores")
            msg.setText("Invalid student score")
            msg.exec()
            self.txtScore.clear()
            
    # Define a function called calculate_average that calculates an average of all previously added student scores.        
    def calculate_average(self):
        # Display a message box that shows the average of all previously added student scores.
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle("Average Scores")
        if(len(self.student_scores_lst) > 0):
            average_value = sum(self.student_scores_lst)/len(self.student_scores_lst)
            msg.setText("Average of all scores: " + str(average_value))
        else:
            msg.setText("No student scores added")

        msg.exec() 
    
    # Define a function called clear that clears all text fields.
    def clear(self):
        self.txtScore.clear()
        self.lstScores.clear()
        # also remove all items from the list
        
        
            


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calculateScore = QtWidgets.QMainWindow()
    ui = Ui_calculateScore()
    ui.setupUi(calculateScore)
    calculateScore.show()
    sys.exit(app.exec())
