# Form implementation generated from reading ui file 'fruitpurchase.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_fruitPurchase(object):
    def setupUi(self, fruitPurchase):
        fruitPurchase.setObjectName("fruitPurchase")
        fruitPurchase.resize(1112, 846)
        self.centralwidget = QtWidgets.QWidget(parent=fruitPurchase)
        self.centralwidget.setObjectName("centralwidget")
        self.lblFruit = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFruit.setGeometry(QtCore.QRect(260, 180, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblFruit.setFont(font)
        self.lblFruit.setObjectName("lblFruit")
        self.cmbFruit = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbFruit.setGeometry(QtCore.QRect(260, 240, 131, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.cmbFruit.setFont(font)
        self.cmbFruit.setObjectName("cmbFruit")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.lblPrice = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPrice.setGeometry(QtCore.QRect(540, 245, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblPrice.setFont(font)
        self.lblPrice.setText("")
        self.lblPrice.setObjectName("lblPrice")
        self.lblQuantity = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblQuantity.setGeometry(QtCore.QRect(260, 310, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblQuantity.setFont(font)
        self.lblQuantity.setObjectName("lblQuantity")
        self.txtQuantity = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtQuantity.setGeometry(QtCore.QRect(550, 330, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtQuantity.setFont(font)
        self.txtQuantity.setObjectName("txtQuantity")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(260, 440, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnCalculate.setFont(font)
        self.btnCalculate.setObjectName("btnCalculate")
        self.lblCost = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblCost.setGeometry(QtCore.QRect(260, 530, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblCost.setFont(font)
        self.lblCost.setObjectName("lblCost")
        self.txtCost = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtCost.setGeometry(QtCore.QRect(560, 550, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtCost.setFont(font)
        self.txtCost.setObjectName("txtCost")
        fruitPurchase.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=fruitPurchase)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 26))
        self.menubar.setObjectName("menubar")
        fruitPurchase.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=fruitPurchase)
        self.statusbar.setObjectName("statusbar")
        fruitPurchase.setStatusBar(self.statusbar)

        self.retranslateUi(fruitPurchase)
        QtCore.QMetaObject.connectSlotsByName(fruitPurchase)
        # Create a new dictionary called fruit_price that will hold the price per pound for each fruit.
        self.fruit_price = {"Apple": 2.50, "Banana": 1.25, "Orange": 3.30, "Grapes": 4.20, "Mango": 3.75}
        # Define the function that is called to display the price when the fruit is selected.
        self.cmbFruit.currentIndexChanged.connect(self.display_price)
        # Define the function that is called when clicking the Calculate button.
        self.btnCalculate.clicked.connect(self.calculate_cost)

    def retranslateUi(self, fruitPurchase):
        _translate = QtCore.QCoreApplication.translate
        fruitPurchase.setWindowTitle(_translate("fruitPurchase", "Fruit Purchase"))
        self.lblFruit.setText(_translate("fruitPurchase", "Select a fruit"))
        self.cmbFruit.setItemText(0, _translate("fruitPurchase", "Select a fruit"))
        self.cmbFruit.setItemText(1, _translate("fruitPurchase", "Apple"))
        self.cmbFruit.setItemText(2, _translate("fruitPurchase", "Banana"))
        self.cmbFruit.setItemText(3, _translate("fruitPurchase", "Orange"))
        self.cmbFruit.setItemText(4, _translate("fruitPurchase", "Grapes"))
        self.cmbFruit.setItemText(5, _translate("fruitPurchase", "Mango"))
        self.lblQuantity.setText(_translate("fruitPurchase", "Enter Quantity"))
        self.btnCalculate.setText(_translate("fruitPurchase", "Calculate"))
        self.lblCost.setText(_translate("fruitPurchase", "Total Cost"))
        
    # Define a function called display_price to display the price per pound based on the fruit selected by the user.    
    def display_price(self):
        # Get the fruit selected by the user and store it in the selected_fruit variable.
        selected_fruit = self.cmbFruit.currentText()
        # Get the price per pound of the fruit selected from the fruit_price dictionary.
        price_of_fruit = self.fruit_price.get(selected_fruit)
        # Display the price of the fruit in a label.
        self.lblPrice.setText("Price per pound: " + str(price_of_fruit))
        
    # Define a function called calculate_cost that calculates the cost of the fruit purchase based on the quantity entered by the user.    
    def calculate_cost(self):
        # Get the quantity entered by the user and store it in the quantity variable and convert it to an integer.
        quantity = self.txtQuantity.text()
        
        # Validate the user entered the Quantity as a number.
        if(quantity.isdigit()):
        
            # Convert the quantity variable to an integer.
            quantity = int(quantity)
            # Get the fruit selected by the user and store it in the selected_fruit variable.
            selected_fruit = self.cmbFruit.currentText()
        
            if(selected_fruit in self.fruit_price.keys()):
                # Get the price of the fruit from the fruit_price dictionary.
                price_of_fruit = self.fruit_price.get(selected_fruit)
                # Calculate the cost of the fruit purchase and round it.
                cost_of_purchase = round(quantity*price_of_fruit, 2)
                # Display the cost of the fruit purchase in the text box.
                self.txtCost.setText(str(cost_of_purchase))
        
            # If user does not select a fruit, display a message box asking the user to select a fruit.
            else:
                msg = QtWidgets.QMessageBox()
                msg.setWindowTitle("Fruit Purchase")
                msg.setText("Select a fruit")
                self.lblPrice.setText("")
                msg.exec()

        # If user does not enter the quantity as a number, display a message box asking the user to enter a valide quantity.
        else:
            msg = QtWidgets.QMessageBox()
            msg.setWindowTitle("Fruit Purchase")
            msg.setText("Please enter a valid number for the Quantity.")
            self.lblPrice.setText("")
            msg.exec()
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fruitPurchase = QtWidgets.QMainWindow()
    ui = Ui_fruitPurchase()
    ui.setupUi(fruitPurchase)
    fruitPurchase.show()
    sys.exit(app.exec())
