# Form implementation generated from reading ui file 'gradecalculator.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox

class Ui_GradeCalculator(object):
    def setupUi(self, GradeCalculator):
        GradeCalculator.setObjectName("GradeCalculator")
        GradeCalculator.resize(1121, 859)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        GradeCalculator.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=GradeCalculator)
        self.centralwidget.setObjectName("centralwidget")
        self.lblScore = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblScore.setGeometry(QtCore.QRect(260, 210, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblScore.setFont(font)
        self.lblScore.setObjectName("lblScore")
        self.txtScore = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtScore.setGeometry(QtCore.QRect(640, 230, 113, 22))
        self.txtScore.setObjectName("txtScore")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(650, 330, 111, 28))
        self.btnCalculate.setObjectName("btnCalculate")
        self.lblGrade = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblGrade.setGeometry(QtCore.QRect(260, 430, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblGrade.setFont(font)
        self.lblGrade.setObjectName("lblGrade")
        self.txtGrade = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtGrade.setGeometry(QtCore.QRect(650, 450, 113, 22))
        self.txtGrade.setObjectName("txtGrade")
        GradeCalculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=GradeCalculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1121, 26))
        self.menubar.setObjectName("menubar")
        GradeCalculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=GradeCalculator)
        self.statusbar.setObjectName("statusbar")
        GradeCalculator.setStatusBar(self.statusbar)

        self.retranslateUi(GradeCalculator)
        QtCore.QMetaObject.connectSlotsByName(GradeCalculator)
        # Define the function that is called when the Calculate button is clicked.
        self.btnCalculate.clicked.connect(self.grade_calculator)
        

    def retranslateUi(self, GradeCalculator):
        _translate = QtCore.QCoreApplication.translate
        GradeCalculator.setWindowTitle(_translate("GradeCalculator", "Grade Calculator"))
        self.lblScore.setText(_translate("GradeCalculator", "Enter Student Score"))
        self.btnCalculate.setText(_translate("GradeCalculator", "Calculate Grade"))
        self.lblGrade.setText(_translate("GradeCalculator", "Student Grade"))
    
    # Define the grade_calculator function to accept a student score and calculate the letter grade.
    def grade_calculator(self):
        # Get the student's score and store it in the input_score variable.
        input_score = self.txtScore.text()
        # Create the grade variable.
        grade = ""
        msg = QMessageBox()
        msg.setWindowTitle("Grade Calculator")
        
        # Validate that the score entered is a number.
        if(input_score.isdigit()):
            # Convert the input_score variable to an integer.
            input_score = int(input_score)
            # Calculate the corresponding letter grade based on the student score.

            if(input_score < 101):
                if(input_score >= 90):
                    grade = "A"
                elif(input_score >= 80):
                    grade = "B"
                elif(input_score >= 70):
                    grade = "C" 
                elif(input_score >= 60):
                    grade = "D" 
                else:
                    grade = "F"
                self.txtGrade.setText(grade) 
            else:
                # Display a message asking the user to enter a valid score.
                msg.setText("Please enter a score between 0 and 100")
                msg.exec()
        
        # Display a message box asking the user to enter a valid score.
        else:
            msg.setText("Please enter a valid score")
            msg.exec()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GradeCalculator = QtWidgets.QMainWindow()
    ui = Ui_GradeCalculator()
    ui.setupUi(GradeCalculator)
    GradeCalculator.show()
    sys.exit(app.exec())
