# Form implementation generated from reading ui file 'evenorodd.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox


class Ui_EvenOrOdd(object):
    def setupUi(self, EvenOrOdd):
        EvenOrOdd.setObjectName("EvenOrOdd")
        EvenOrOdd.resize(1118, 848)
        self.centralwidget = QtWidgets.QWidget(parent=EvenOrOdd)
        self.centralwidget.setObjectName("centralwidget")
        self.lblNumber = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblNumber.setGeometry(QtCore.QRect(320, 270, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblNumber.setFont(font)
        self.lblNumber.setObjectName("lblNumber")
        self.txtNumber = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtNumber.setGeometry(QtCore.QRect(540, 290, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtNumber.setFont(font)
        self.txtNumber.setObjectName("txtNumber")
        self.btnCheck = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCheck.setGeometry(QtCore.QRect(550, 360, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnCheck.setFont(font)
        self.btnCheck.setObjectName("btnCheck")
        self.lblResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(320, 430, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblResult.setFont(font)
        self.lblResult.setObjectName("lblResult")
        self.txtResult = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtResult.setGeometry(QtCore.QRect(540, 450, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtResult.setFont(font)
        self.txtResult.setObjectName("txtResult")
        EvenOrOdd.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=EvenOrOdd)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1118, 26))
        self.menubar.setObjectName("menubar")
        EvenOrOdd.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=EvenOrOdd)
        self.statusbar.setObjectName("statusbar")
        EvenOrOdd.setStatusBar(self.statusbar)

        self.retranslateUi(EvenOrOdd)
        QtCore.QMetaObject.connectSlotsByName(EvenOrOdd)
        #Event: Execute function evenoroddcheck when the Check button is clicked
        self.btnCheck.clicked.connect(self.evenoroddcheck)
    
    def retranslateUi(self, EvenOrOdd):
        _translate = QtCore.QCoreApplication.translate
        EvenOrOdd.setWindowTitle(_translate("EvenOrOdd", "Even or Odd"))
        self.lblNumber.setText(_translate("EvenOrOdd", "Enter a number"))
        self.btnCheck.setText(_translate("EvenOrOdd", "Check"))
        self.lblResult.setText(_translate("EvenOrOdd", "Result"))

    # Define a function called evenoroddcheck that accepts a number from the user and displays a message to indicate if the number is even or odd.    
    def evenoroddcheck(self):
        # Get the number from the user.
        input_number = self.txtNumber.text()
        
        # Validate the user has entered a valid number.
        if(input_number.isdigit()):
            
            # Evaluate the input_number to determine if it is even or odd.
            input_number = int(input_number)
            if(input_number%2 == 0):
                self.txtResult.setText("Number is even")
            else:
                self.txtResult.setText("Number is odd")
        else:
            msg = QMessageBox()
            msg.setText("Please enter a valid number")
            msg.setWindowTittle("Even or Odd")
            msg.exec()
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EvenOrOdd = QtWidgets.QMainWindow()
    ui = Ui_EvenOrOdd()
    ui.setupUi(EvenOrOdd)
    EvenOrOdd.show()
    sys.exit(app.exec())
