# Generated by Django 4.2 on 2025-04-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coursedetails',
            fields=[
                ('courseid', models.IntegerField(primary_key=True, serialize=False)),
                ('coursetitle', models.CharField(max_length=100)),
                ('coursename', models.CharField(max_length=100)),
                ('studentsenrolled', models.IntegerField()),
                ('coursedept', models.CharField(max_length=100)),
                ('instructorname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Studentdetails',
            fields=[
                ('studentid', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
