# Generated by Django 4.2 on 2025-04-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollmentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=100)),
                ('coursetitle', models.CharField(max_length=100)),
                ('coursename', models.CharField(max_length=100)),
            ],
        ),
    ]
