# Form implementation generated from reading ui file 'collegefeecalculator.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_collegeFeeCalculator(object):
    def setupUi(self, collegeFeeCalculator):
        collegeFeeCalculator.setObjectName("collegeFeeCalculator")
        collegeFeeCalculator.resize(1126, 856)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        collegeFeeCalculator.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=collegeFeeCalculator)
        self.centralwidget.setObjectName("centralwidget")
        self.lblFirstName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFirstName.setGeometry(QtCore.QRect(270, 180, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblFirstName.setFont(font)
        self.lblFirstName.setObjectName("lblFirstName")
        self.txtFirstName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtFirstName.setGeometry(QtCore.QRect(600, 200, 191, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtFirstName.setFont(font)
        self.txtFirstName.setObjectName("txtFirstName")
        self.lblLastName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblLastName.setGeometry(QtCore.QRect(270, 250, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblLastName.setFont(font)
        self.lblLastName.setObjectName("lblLastName")
        self.txtLastName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtLastName.setGeometry(QtCore.QRect(600, 270, 191, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtLastName.setFont(font)
        self.txtLastName.setObjectName("txtLastName")
        self.lblAge = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAge.setGeometry(QtCore.QRect(270, 320, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblAge.setFont(font)
        self.lblAge.setObjectName("lblAge")
        self.txtAge = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtAge.setGeometry(QtCore.QRect(600, 340, 191, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtAge.setFont(font)
        self.txtAge.setObjectName("txtAge")
        self.cmbMajor = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbMajor.setGeometry(QtCore.QRect(600, 410, 191, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.cmbMajor.setFont(font)
        self.cmbMajor.setObjectName("cmbMajor")
        self.cmbMajor.addItem("")
        self.cmbMajor.addItem("")
        self.cmbMajor.addItem("")
        self.cmbMajor.addItem("")
        self.lblMajor = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblMajor.setGeometry(QtCore.QRect(270, 390, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblMajor.setFont(font)
        self.lblMajor.setObjectName("lblMajor")
        self.chkResidency = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.chkResidency.setGeometry(QtCore.QRect(650, 470, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.chkResidency.setFont(font)
        self.chkResidency.setObjectName("chkResidency")
        self.lblResidency = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblResidency.setGeometry(QtCore.QRect(270, 460, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblResidency.setFont(font)
        self.lblResidency.setObjectName("lblResidency")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(490, 540, 101, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnCalculate.setFont(font)
        self.btnCalculate.setObjectName("btnCalculate")
        self.btnClear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(370, 700, 101, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.btnExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(620, 700, 101, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnExit.setFont(font)
        self.btnExit.setObjectName("btnExit")
        self.lblTittle = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTittle.setGeometry(QtCore.QRect(240, 90, 671, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.lblTittle.setFont(font)
        self.lblTittle.setObjectName("lblTittle")
        self.lblFee = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFee.setGeometry(QtCore.QRect(270, 600, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblFee.setFont(font)
        self.lblFee.setObjectName("lblFee")
        self.txtFee = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtFee.setGeometry(QtCore.QRect(602, 610, 191, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtFee.setFont(font)
        self.txtFee.setObjectName("txtFee")
        collegeFeeCalculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=collegeFeeCalculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1126, 26))
        self.menubar.setObjectName("menubar")
        collegeFeeCalculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=collegeFeeCalculator)
        self.statusbar.setObjectName("statusbar")
        collegeFeeCalculator.setStatusBar(self.statusbar)

        self.retranslateUi(collegeFeeCalculator)
        QtCore.QMetaObject.connectSlotsByName(collegeFeeCalculator)

        # Define the function that is executed when clicking the Calculate, Clear, and Exit buttons.
        self.btnCalculate.clicked.connect(self.calculate_fee)
        self.btnClear.clicked.connect(self.clear)
        self.btnExit.clicked.connect(self.exit_application)

    def retranslateUi(self, collegeFeeCalculator):
        _translate = QtCore.QCoreApplication.translate
        collegeFeeCalculator.setWindowTitle(_translate("collegeFeeCalculator", "College Fee Calculator"))
        self.lblFirstName.setText(_translate("collegeFeeCalculator", "Enter First Name"))
        self.lblLastName.setText(_translate("collegeFeeCalculator", "Enter Last Name"))
        self.lblAge.setText(_translate("collegeFeeCalculator", "Enter Age"))
        self.cmbMajor.setItemText(0, _translate("collegeFeeCalculator", "Computer Science"))
        self.cmbMajor.setItemText(1, _translate("collegeFeeCalculator", "Business Administration"))
        self.cmbMajor.setItemText(2, _translate("collegeFeeCalculator", "Arts and Humanities"))
        self.cmbMajor.setItemText(3, _translate("collegeFeeCalculator", "Sciences"))
        self.lblMajor.setText(_translate("collegeFeeCalculator", "Select Major"))
        self.chkResidency.setText(_translate("collegeFeeCalculator", "In-State"))
        self.lblResidency.setText(_translate("collegeFeeCalculator", "Select Residency Status"))
        self.btnCalculate.setText(_translate("collegeFeeCalculator", "Calculate Fee"))
        self.btnClear.setText(_translate("collegeFeeCalculator", "Clear Form"))
        self.btnExit.setText(_translate("collegeFeeCalculator", "Exit"))
        self.lblTittle.setText(_translate("collegeFeeCalculator", "College Enrollment Fee Calculator"))
        self.lblFee.setText(_translate("collegeFeeCalculator", "College Enrollment Fee"))
    
    # Define the calculate_fee function to calculate the college enrollment fee when the Calculate Fee button is clicked.
    def calculate_fee(self):
        # Get the student's First Name and store it in the first_name variable.
        first_name = self.txtFirstName.text()
        # Get the student's Last Name and store it in the last_name variable.
        last_name = self.txtLastName.text()
        # Get the student's Age and store it in the age variable.
        age = self.txtAge.text()
        # Get the student's Major and store it in the major variable.
        major = self.cmbMajor.currentText()
        # Define the fee variable and set it to 0.
        fee = 0
        
        # Validate that user has entered the First Name and Last Name as letters and has entered the Age as a number.
        if(first_name.isalpha() and last_name.isalpha() and age.isdigit()):
            
            # Evaluate the Residency Status checkbox to determine if in-state or out-of-state tuition fees apply.
            # If the Residency Status checkbox is checked, set the fee variable to 10,000.
            if(self.chkResidency.isChecked()):
                fee = 10000
            # If the Residency Status checkbox is not checked, set the fee variable to 15,000.
            else:
                fee = 15000
            
            # Evaluate the Major selected in the drop-down box to determine the additional Program Fees.
            # If the Major selected is Computer Science, increase the fee variable by 2,000.
            if(major == "Computer Science"):
                fee = fee + 2000
            # If the Major selected is Business Administration, increase the fee variable by 1,500.
            elif(major == "Business Administration"):
                fee = fee + 1500
            # If the Major selected is Arts and Humanities, increase the fee variable by 1,000.
            elif(major == "Arts and Humanities"):
                fee = fee + 1000
            # If the Major selected is Sciences, increase the fee variable by 1,800.
            else:
                fee = fee + 1800
            
            # Set the text of the txtFee text box equal to the fee variable. Formatted the total amount as a currency value.
            self.txtFee.setText('${:,.2f}'.format(fee))
        
        else:
            # Display an error message to the user if the First Name, Last Name, or Age is not filled in.
            msg = QtWidgets.QMessageBox()
            # Set the title of the Message Box to College Fee Calculator.
            msg.setWindowTitle("College Fee Calculator")
            # Set the display text of the Message Box.
            msg.setText("Please enter valid inputs for the First Name, Last Name, and Age")
            # Execute the Message Box
            msg.exec()
    
    # Define the clear function that resets all fields to their default values when the Clear button is clicked.
    def clear(self):
        # Clears the First Name text box.
        self.txtFirstName.clear()
        # Clears the Last Name text box.
        self.txtLastName.clear()
        # Clears the Age text box.
        self.txtAge.clear()
        # Un-checks the Residency checkbox.
        self.chkResidency.setChecked(False)
        # Re-set the Major combo box to Computer Science.
        self.cmbMajor.setCurrentText("Computer Science")
        # Clears the Calculated Fee text box.
        self.txtFee.clear()
    
    # Define the exit_application function that closes the application when the Exit button is clicked.
    def exit_application(self):
        #Close the application when the Exit button is clicked.
        QtWidgets.QApplication.quit()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    collegeFeeCalculator = QtWidgets.QMainWindow()
    ui = Ui_collegeFeeCalculator()
    ui.setupUi(collegeFeeCalculator)
    collegeFeeCalculator.show()
    sys.exit(app.exec())
