# Form implementation generated from reading ui file 'firewoodapp.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
# Importing the QTableWidgetItem from QtWidgets.
from PyQt6.QtWidgets import QTableWidgetItem
# Importing the pymysql package and calling it with an alias mdb
import pymysql as mdb

class Ui_firewoodApp(object):
    def setupUi(self, firewoodApp):
        firewoodApp.setObjectName("firewoodApp")
        firewoodApp.resize(1118, 851)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        firewoodApp.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=firewoodApp)
        self.centralwidget.setObjectName("centralwidget")
        self.tbFirewoodApp = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tbFirewoodApp.setGeometry(QtCore.QRect(0, 0, 1101, 791))
        self.tbFirewoodApp.setObjectName("tbFirewoodApp")
        self.tabDashboard = QtWidgets.QWidget()
        self.tabDashboard.setObjectName("tabDashboard")
        self.btnPurchase = QtWidgets.QPushButton(parent=self.tabDashboard)
        self.btnPurchase.setGeometry(QtCore.QRect(230, 250, 121, 51))
        self.btnPurchase.setObjectName("btnPurchase")
        self.btnSearch = QtWidgets.QPushButton(parent=self.tabDashboard)
        self.btnSearch.setGeometry(QtCore.QRect(470, 250, 121, 51))
        self.btnSearch.setObjectName("btnSearch")
        self.btnDisplay = QtWidgets.QPushButton(parent=self.tabDashboard)
        self.btnDisplay.setGeometry(QtCore.QRect(710, 250, 121, 51))
        self.btnDisplay.setObjectName("btnDisplay")
        self.btnExit = QtWidgets.QPushButton(parent=self.tabDashboard)
        self.btnExit.setGeometry(QtCore.QRect(470, 440, 121, 51))
        self.btnExit.setObjectName("btnExit")
        self.tbFirewoodApp.addTab(self.tabDashboard, "")
        self.tabPurchase = QtWidgets.QWidget()
        self.tabPurchase.setObjectName("tabPurchase")
        self.lblTransactionId = QtWidgets.QLabel(parent=self.tabPurchase)
        self.lblTransactionId.setGeometry(QtCore.QRect(290, 140, 201, 41))
        self.lblTransactionId.setObjectName("lblTransactionId")
        self.lblCustomerName = QtWidgets.QLabel(parent=self.tabPurchase)
        self.lblCustomerName.setGeometry(QtCore.QRect(290, 200, 201, 41))
        self.lblCustomerName.setObjectName("lblCustomerName")
        self.txtTransactionId = QtWidgets.QLineEdit(parent=self.tabPurchase)
        self.txtTransactionId.setGeometry(QtCore.QRect(590, 150, 171, 22))
        self.txtTransactionId.setObjectName("txtTransactionId")
        self.txtCustomerName = QtWidgets.QLineEdit(parent=self.tabPurchase)
        self.txtCustomerName.setGeometry(QtCore.QRect(590, 210, 171, 22))
        self.txtCustomerName.setObjectName("txtCustomerName")
        self.cmbType = QtWidgets.QComboBox(parent=self.tabPurchase)
        self.cmbType.setGeometry(QtCore.QRect(590, 270, 171, 22))
        self.cmbType.setObjectName("cmbType")
        self.lblType = QtWidgets.QLabel(parent=self.tabPurchase)
        self.lblType.setGeometry(QtCore.QRect(290, 260, 201, 41))
        self.lblType.setObjectName("lblType")
        self.lblQuantity = QtWidgets.QLabel(parent=self.tabPurchase)
        self.lblQuantity.setGeometry(QtCore.QRect(290, 320, 201, 41))
        self.lblQuantity.setObjectName("lblQuantity")
        self.txtQuantity = QtWidgets.QLineEdit(parent=self.tabPurchase)
        self.txtQuantity.setGeometry(QtCore.QRect(590, 330, 171, 22))
        self.txtQuantity.setObjectName("txtQuantity")
        self.btnTotal = QtWidgets.QPushButton(parent=self.tabPurchase)
        self.btnTotal.setGeometry(QtCore.QRect(450, 410, 121, 28))
        self.btnTotal.setObjectName("btnTotal")
        self.lblTotal = QtWidgets.QLabel(parent=self.tabPurchase)
        self.lblTotal.setGeometry(QtCore.QRect(290, 460, 201, 41))
        self.lblTotal.setObjectName("lblTotal")
        self.txtTotal = QtWidgets.QLineEdit(parent=self.tabPurchase)
        self.txtTotal.setGeometry(QtCore.QRect(590, 470, 171, 22))
        self.txtTotal.setReadOnly(True)
        self.txtTotal.setObjectName("txtTotal")
        self.btnPurchase_2 = QtWidgets.QPushButton(parent=self.tabPurchase)
        self.btnPurchase_2.setGeometry(QtCore.QRect(450, 540, 121, 28))
        self.btnPurchase_2.setObjectName("btnPurchase_2")
        self.tbFirewoodApp.addTab(self.tabPurchase, "")
        self.tabSearch = QtWidgets.QWidget()
        self.tabSearch.setObjectName("tabSearch")
        self.cmbFirewoodType = QtWidgets.QComboBox(parent=self.tabSearch)
        self.cmbFirewoodType.setGeometry(QtCore.QRect(590, 50, 171, 22))
        self.cmbFirewoodType.setObjectName("cmbFirewoodType")
        self.lblFirewoodType = QtWidgets.QLabel(parent=self.tabSearch)
        self.lblFirewoodType.setGeometry(QtCore.QRect(290, 40, 201, 41))
        self.lblFirewoodType.setObjectName("lblFirewoodType")
        self.btnAverage = QtWidgets.QPushButton(parent=self.tabSearch)
        self.btnAverage.setGeometry(QtCore.QRect(410, 110, 201, 28))
        self.btnAverage.setObjectName("btnAverage")
        self.lblAverage = QtWidgets.QLabel(parent=self.tabSearch)
        self.lblAverage.setGeometry(QtCore.QRect(290, 160, 201, 41))
        self.lblAverage.setObjectName("lblAverage")
        self.txtAverage = QtWidgets.QLineEdit(parent=self.tabSearch)
        self.txtAverage.setGeometry(QtCore.QRect(590, 170, 171, 22))
        self.txtAverage.setObjectName("txtAverage")
        self.btnDisplayData = QtWidgets.QPushButton(parent=self.tabSearch)
        self.btnDisplayData.setGeometry(QtCore.QRect(410, 230, 201, 28))
        self.btnDisplayData.setObjectName("btnDisplayData")
        self.firewoodTableWidget = QtWidgets.QTableWidget(parent=self.tabSearch)
        self.firewoodTableWidget.setGeometry(QtCore.QRect(290, 300, 471, 351))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.firewoodTableWidget.setFont(font)
        self.firewoodTableWidget.setObjectName("firewoodTableWidget")
        self.firewoodTableWidget.setColumnCount(0)
        self.firewoodTableWidget.setRowCount(0)
        self.btnDashboard = QtWidgets.QPushButton(parent=self.tabSearch)
        self.btnDashboard.setGeometry(QtCore.QRect(410, 690, 201, 28))
        self.btnDashboard.setObjectName("btnDashboard")
        self.tbFirewoodApp.addTab(self.tabSearch, "")
        self.tabDisplay = QtWidgets.QWidget()
        self.tabDisplay.setObjectName("tabDisplay")
        self.displayTableWidget = QtWidgets.QTableWidget(parent=self.tabDisplay)
        self.displayTableWidget.setGeometry(QtCore.QRect(10, 100, 1091, 571))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.displayTableWidget.setFont(font)
        self.displayTableWidget.setObjectName("displayTableWidget")
        self.displayTableWidget.setColumnCount(0)
        self.displayTableWidget.setRowCount(0)
        self.tbFirewoodApp.addTab(self.tabDisplay, "")
        firewoodApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=firewoodApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1118, 28))
        self.menubar.setObjectName("menubar")
        firewoodApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=firewoodApp)
        self.statusbar.setObjectName("statusbar")
        firewoodApp.setStatusBar(self.statusbar)

        self.retranslateUi(firewoodApp)
        self.tbFirewoodApp.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(firewoodApp)

        # Define the connection to open the database. 
        self.connection = self.createdbconnection()
        # Create a new dictionary called price_dictionary that will be populated using the load_data function.
        self.price_dictionary = self.load_data("data.txt")      
        # Define the function that is executed when clicking the Purchase button on the Dashboard.
        self.btnPurchase.clicked.connect(self.purchase_goto_tab)
        # Define the function that is executed when clicking the Search button on the Dashboard.
        self.btnSearch.clicked.connect(self.search_goto_tab)
        # Define the function that is executed when clicking the Display button on the Dashboard.
        self.btnDisplay.clicked.connect(self.display_goto_tab)
        # Define the function that is executed when clicking the Exit button on the Dashboard.
        self.btnExit.clicked.connect(self.exit_application)
        # Define the function that is executed when clicking on the Purchase, Search, or Display tabs.
        self.tbFirewoodApp.currentChanged.connect(self.tab_change)
        # Define the function that is executed when clicking the Display Total button on the Purchase tab.
        self.btnTotal.clicked.connect(self.display_total)
        # Define the function that is executed when clicking the Purchase button on the Purchase tab.
        self.btnPurchase_2.clicked.connect(self.purchase_made)
        # Define the function that is executed when clicking the Calculate Average Price button on the Search tab.
        self.btnAverage.clicked.connect(self.calculate_average)
        # Define the function that is executed when clicking the Display Data button on the Search tab.
        self.btnDisplayData.clicked.connect(self.display_data)
        # Define the function that ie executed when clicking the Dashboard button on the Search tab.
        self.btnDashboard.clicked.connect(self.dashboard_return)

    def retranslateUi(self, firewoodApp):
        _translate = QtCore.QCoreApplication.translate
        firewoodApp.setWindowTitle(_translate("firewoodApp", "Firewood App"))
        self.btnPurchase.setText(_translate("firewoodApp", "Purchase"))
        self.btnSearch.setText(_translate("firewoodApp", "Search"))
        self.btnDisplay.setText(_translate("firewoodApp", "Display"))
        self.btnExit.setText(_translate("firewoodApp", "Exit"))
        self.tbFirewoodApp.setTabText(self.tbFirewoodApp.indexOf(self.tabDashboard), _translate("firewoodApp", "Dashboard"))
        self.lblTransactionId.setText(_translate("firewoodApp", "Transaction ID"))
        self.lblCustomerName.setText(_translate("firewoodApp", "Customer Name"))
        self.lblType.setText(_translate("firewoodApp", "Firewood Type"))
        self.lblQuantity.setText(_translate("firewoodApp", "Quantity"))
        self.btnTotal.setText(_translate("firewoodApp", "Display Total"))
        self.lblTotal.setText(_translate("firewoodApp", "Total"))
        self.btnPurchase_2.setText(_translate("firewoodApp", "Purchase"))
        self.tbFirewoodApp.setTabText(self.tbFirewoodApp.indexOf(self.tabPurchase), _translate("firewoodApp", "Purchase"))
        self.lblFirewoodType.setText(_translate("firewoodApp", "Firewood Type"))
        self.btnAverage.setText(_translate("firewoodApp", "Calculate Average Price"))
        self.lblAverage.setText(_translate("firewoodApp", "Average Price"))
        self.btnDisplayData.setText(_translate("firewoodApp", "Display Data"))
        self.btnDashboard.setText(_translate("firewoodApp", "Dashboard"))
        self.tbFirewoodApp.setTabText(self.tbFirewoodApp.indexOf(self.tabSearch), _translate("firewoodApp", "Search"))
        self.tbFirewoodApp.setTabText(self.tbFirewoodApp.indexOf(self.tabDisplay), _translate("firewoodApp", "Display"))

    # Define the createdbconnection function to open a connection to the finalprojectdb database.
    def createdbconnection(self):
        try:
            # Create connectionobj object to open connection to the finalprojectdb database.
            connectionobj = mdb.connect(host="localhost", user="studentuser", password="studentuser", database="finalprojectdb")
            # Print a message to indicate that database connection was successful. 
            print("Connected to DB")
            return connectionobj
        
        # Generic exception block for all other unexpected errors
        except Exception as e:
            # Print an error message to indicate there was an error connecting to the database.
            print("Error connecting to DB")
            print(e)
            return None

    # Define the load_data function to read each line of the data.txt file and load into a dictionary called price_dictionary.
    def load_data(self, file_name):
        try:
            # Create an empty dictionary called price_dictionary.
            price_dictionary = {}
            # Read each line of the data.txt file.
            with open(file_name, "r") as fname:
                for line in fname:
                    # strip() will remove extra whitespaces before and after the text.
                    # split() will split the data based on the delimiter of ",".
                    wood_type, wood_price = line.strip().split(",")
                    # Add a new key value pair to the dictionary.
                    price_dictionary[wood_type] = int(wood_price)
            return price_dictionary
            
        # Specific exception block to handle file not found error
        except FileNotFoundError:
            print("The file does not exist")
        # Generic exception block for all other unexpected errors
        except Exception as e:
            print(e)
    
    # Define the purchase_goto_tab function to change to the Purchase tab of the Firewood tab widget when clicking on the Display button on the Dashboard.
    def purchase_goto_tab(self):
        try:
            # Change to the Purchase tab of the FirewoodApp tab widget.
            self.tbFirewoodApp.setCurrentIndex(1)
    
        # Generic exception block for all other unexpected errors
        except Exception as e:
            print(e)
      
    # Define the display_total function to accept the user inputs and display the total price on the Purchase tab.
    def display_total(self):
        try:          
            # Get the Quantity and store it in the quantity variable.
            quantity = self.txtQuantity.text()
                      
            # Get the customer's Firewood Type selection and store it in the current_selection variable.
            current_selection = self.cmbType.currentText()
            
            # Get the price of the firewood type from the price dictionary based on the current_selection variable.
            unit_price = self.price_dictionary.get(current_selection)
            
            # Validate the user has entered the Quantity as a number.
            if(quantity.isdigit()):
                
                # Convert the quantity variable from a text to a integer value.
                quantity = int(quantity)
                # Set the tax rate to 8%
                tax_rate = 0.08
                # Calculate the total price based on the per unit price of the firewood type and the quantity entered.
                total_price = (unit_price * quantity) * (1 + tax_rate)
                # Set the text of the txtTotal text box equal to the total_price variable. Formatted the total amount as a currency value.
                self.txtTotal.setText('${:,.2f}'.format(total_price))
            
            else:
                # Display an error message to the user if the Quantity is not correctly filled in.
                msg = QtWidgets.QMessageBox()
                # Set the title of the Message Box to Firewood App.
                msg.setWindowTitle("Firewood App")
                # Set the display text of the Message Box.
                msg.setText("Please enter a valid input for the Quantity.")
                # Execute the Message Box
                msg.exec()
                
        # Generic exception block for all other unexpected errors
        except Exception as e:
            print(e)
    
    # Define the purchase_made function to accept the user inputs and insert the purchase into the firewood_sales table of the finalprojectdb.
    def purchase_made(self):
        try:          
            # Get the Transaction ID and store it in the transactionid variable.
            transactionid = self.txtTransactionId.text()
            # Get the Customer's Name and store it in the customername variable.
            customername = self.txtCustomerName.text()
            # Get the Quantity and store it in the quantity variable.
            quantity = self.txtQuantity.text()
            
            # Get the customer's Firewood Type selection and store it in the current_selection variable.
            current_selection = self.cmbType.currentText()
            
            # Get the price of the firewood type from the price dictionary based on the current_selection variable.
            unit_price = self.price_dictionary.get(current_selection)
            
            # Create a cursor object
            cursor = self.connection.cursor()
            
            # Validate the user has entered the Customer Name as letters and has entered the Transaction ID and Quantity as numbers.
            if(customername.replace(" ", "").isalpha() and transactionid.isdigit() and quantity.isdigit()):
                
                # Convert the quantity variable from a text to a integer value.
                quantity = int(quantity)
                # Set the tax rate to 8%
                tax_rate = 0.08
                # Calculate the total price based on the per unit price of the firewood type and the quantity entered.
                total_price = (unit_price * quantity) * (1 + tax_rate)
            
                # Insert the user inputs and total price into the firewood_sales table of the finalprojectdb database.
                cursor.execute("insert into firewood_sales (transactionid, customername, type, quantity, total) values (%s,%s,%s, %s, %s)",[transactionid, customername, current_selection, quantity, total_price])
                self.connection.commit()
                # Print a message to indicate the data was successfully added to the firewood_sales table.
                print("Added data to the table")
                # Display a message to indicate successful addition of data
                msg = QtWidgets.QMessageBox()
                # Set the title of the message box to Firewood App
                msg.setWindowTitle("Firewood App")
                # Set the display text of the message box
                msg.setText("Transaction successful.")
                # Execute the message box
                msg.exec()
                
                # Clear the text boxes
                # Clear the Transaction ID text box
                self.txtTransactionId.clear()
                # Clear the Customer Name text box
                self.txtCustomerName.clear()
                # Clear the Quantity text box
                self.txtQuantity.clear()
                # Clear the Total text box
                self.txtTotal.clear()
                # Re-set the Firewood Type combo box to a default value of Oak.
                self.cmbType.setCurrentIndex(0)
            
            else:
                # Display an error message to the user if the Transaction ID, Customer Name, or Quantity is not correctly filled in.
                msg = QtWidgets.QMessageBox()
                # Set the title of the Message Box to Firewood App.
                msg.setWindowTitle("Firewood App")
                # Set the display text of the Message Box.
                msg.setText("Please enter a valid inputs for the Transaction ID, Customer Name, and Quantity.")
                # Execute the Message Box
                msg.exec()
            
        # Generic exception block for all other unexpected errors
        except Exception as e:
            print(e)
            
        # Close the cursor object that was created above.
        finally:
            cursor.close() 

    # Define the search_goto_tab function to change to the Search tab of the Firewood tab widget when clicking on the Display button on the Dashboard.
    def search_goto_tab(self):
        try:
            # Change to the Search tab of the FirewoodApp tab widget.
            self.tbFirewoodApp.setCurrentIndex(2)
                
        # Generic exception block for all other unexpected errors
        except Exception as e:
            print(e)
    
    # Define the calculate_average function to calculate and display the average total price for all transactions for the selected firewood type.
    def calculate_average(self):
        try:
            # Get the customer's Firewood Type selection and store it in the firewood_type variable.
            firewood_type = self.cmbFirewoodType.currentText()
            
            # Create a cursor object.
            cursor = self.connection.cursor()
            
            # Calculate the average total price for all of the records of the selected firewood type from the firewood_sales table.
            # If firewood_type = Oak, select the database table records for Oak.
            if(firewood_type == "Oak"):
                cursor.execute("select avg(total) as average_price from firewood_sales where type = 'Oak'")
                results = cursor.fetchall()
            # If firewood_type = Maple, select the database table records for Maple.
            elif(firewood_type == "Maple"):
                cursor.execute("select avg(total) as average_price from firewood_sales where type = 'Maple'")
                results = cursor.fetchall()
            # If firewood_type = Birch, select the database table records for Birch.
            elif(firewood_type == "Birch"):
                cursor.execute("select avg(total) as average_price from firewood_sales where type = 'Birch'")
                results = cursor.fetchall()
            # Otherwise, firewood_type = Apple, so select the database table records for Apple.
            else:
                cursor.execute("select avg(total) as average_price from firewood_sales where type = 'Apple'")
                results = cursor.fetchall()
                                  
            # Set the text of the txtAverage text box equal to the results variable. Formatted the total amount as a currency value.
            for average in results:
                self.txtAverage.setText('${:,.2f}'.format(float(average[0])))
            
        # Generic exception block for all other unexpected errors
        except Exception as e:
            print(e)   
        
        # Close the cursor object that was created above.
        finally:
            cursor.close()
        
    # Define the display_data function to display all rows of data in the firewood_sales table of the finalprojecdb database for a selected
    # Firewood Type in the Table Widget object on the Search tab.
    def display_data(self):
        try:
            # Get the customer's Firewood Type selection and store it in the firewood_type variable.
            firewood_type = self.cmbFirewoodType.currentText()
            
            # Create a cursor object.
            cursor = self.connection.cursor()
            
            # Select all records in the firewood_sales table for the selected firewood_type.
            # If firewood_type = Oak, select the database table records for Oak.
            if(firewood_type == "Oak"):
                cursor.execute("select * from firewood_sales where type = 'Oak'")
                results = cursor.fetchall()
            # If firewood_type == "Maple", select the database records for Maple.
            elif(firewood_type == "Maple"):
                cursor.execute("select * from firewood_sales where type = 'Maple'")
                results = cursor.fetchall()
            # If firewood_type == "Birch", select the database records for Birch.
            elif(firewood_type == "Birch"):
                cursor.execute("select * from firewood_sales where type = 'Birch'")
                results = cursor.fetchall()
            # Then the firewood_type is "Apple", so select the database records for Apple.
            else:
                cursor.execute("select * from firewood_sales where type = 'Apple'")
                results = cursor.fetchall()
            
            # Find the number of rows in the firewood_sales table.
            row_count = len(results)
            # Find the number of columns in the firewood_sales table.
            column_count = len(cursor.description)
            # Print the rows in the firewood_sales table.
            print(results)
            # Print the column information for the firewood_sales table.
            print(cursor.description)
        
            # Set the row count for the firewoodTableWidget.
            self.firewoodTableWidget.setRowCount(row_count)
            # Set the column count for the firewoodTableWidget.
            self.firewoodTableWidget.setColumnCount(column_count)
            # Add the column headers to the firewoodTableWidget.
            column_name_lst = ['ID', 'Name', 'Type', 'Quantity', 'Total']
            # Set the column headers for the firewoodTableWidget.
            self.firewoodTableWidget.setHorizontalHeaderLabels(column_name_lst)
            
            # Use enumerate(results) to access the row number and the row data.
            for rowindex, rowdata in enumerate(results):
                # Use enumerate(results) to access the column number and the column data within each row.
                for columnindex, data in enumerate(rowdata):
                    # Display the data for each row and column index in the Table Widget.
                    self.firewoodTableWidget.setItem(rowindex, columnindex, QTableWidgetItem(str(data)))
        
        # Generic exception block for all other unexpected errors        
        except Exception as e:
            print(e)
            
        # Close the cursor object that was created above.
        finally:
            cursor.close()
    
    # Define the display_goto_tab function to change to the Display tab of the Firewood tab widget when clicking on the Display button on the Dashboard.
    def display_goto_tab(self):
        try:
            # Change to the Display tab of the FirewoodApp tab widget.
            self.tbFirewoodApp.setCurrentIndex(3)
        
        # Generic exception block for all other unexpected errors        
        except Exception as e:
            print(e)
        
    # Define the tab_change function to either load the price_dictionary into the Firewood Type combo box on the Purchase and Search tabs or to display all rows of data in the firewood_sales table of the finalprojecdb database
    # in the Table Widget object on the Display tab.
    def tab_change(self, index):
        try:
            # Create a cursor object.
            cursor = self.connection.cursor()
            
            # If the user goes to the Purchase tab, load the Firewood Type combo box from the price_dictionary unless the combo box selection is already loaded.
            if(index == 1):
                if(self.cmbType.currentText() == ""):
                    # Get the wood_type from the price dictionary and load it into the dictionary_keys variable.
                    dictionary_keys = self.price_dictionary.keys()
                    # Load the Firewood Type combo box with the wood_type dictionary keys from the price dictionary.
                    self.cmbType.addItems(dictionary_keys)
            
            # If the user goes to the Search tab, load the Firewood Type combo box from the price_dictionary unless the combo box selection is already loaded.
            elif(index == 2):
                if(self.cmbFirewoodType.currentText() == ""):
                    # Get the wood_type from the price dictionary and load it into the dictionary_keys variable.
                    dictionary_keys = self.price_dictionary.keys()
                    # Load the Firewood Type combo box with the wood_type dictionary keys from the price dictionary.
                    self.cmbFirewoodType.addItems(dictionary_keys)
            
            # If the user goes to the Display tab, display all rows of data in the firewood_sales table of the finalprojecdb database in the Table Widget object on the Display tab.
            else:
                # Select all records in the firewood_sales table.
                cursor.execute("select * from firewood_sales")
                results = cursor.fetchall()
                # Find the number of rows in the firewood_sales table.
                row_count = len(results)
                # Find the number of columns in the firewood_sales table.
                column_count = len(cursor.description)
                # Print the rows in the firewood_sales table.
                print(results)
                # Print the column information for the firewood_sales table.
                print(cursor.description)
        
                # Set the row count for the displayTableWidget.
                self.displayTableWidget.setRowCount(row_count)
                # Set the column count for the displayTableWidget.
                self.displayTableWidget.setColumnCount(column_count)
                # Add the column headers to the displayTableWidget.
                column_name_lst = ['ID', 'Name', 'Type', 'Quantity', 'Total']
                # Set the column headers for the displayTableWidget.
                self.displayTableWidget.setHorizontalHeaderLabels(column_name_lst)
            
                # Use enumerate(results) to access the row number and the row data.
                for rowindex, rowdata in enumerate(results):
                    # Use enumerate(results) to access the column number and the column data within each row.
                    for columnindex, data in enumerate(rowdata):
                        # Display the data for each row and column index in the Table Widget.
                        self.displayTableWidget.setItem(rowindex, columnindex, QTableWidgetItem(str(data)))
        
        # Generic exception block for all other unexpected errors        
        except Exception as e:
            print(e)
            
        # Close the cursor object that was created above.
        finally:
            cursor.close()
    
    # Define the dashboard_return to return the user to the Dashboard tab of the Tab Widget when the Dashboard button on the Search tab is clicked.
    def dashboard_return(self):
        try:
            # Set the current index to the Dashboard tab.
            self.tbFirewoodApp.setCurrentIndex(0)
        
        # Generic exception block for all other unexpected errors
        except Exception as e:
            print(e)
    
    # Define the exit_application function that closes the application when the Exit button is clicked.
    def exit_application(self):
        try:
            #Close the application when the Exit button is clicked.
            QtWidgets.QApplication.quit()  
        
        # Generic exception block for all other unexpected errors
        except Exception as e:
            print(e)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    firewoodApp = QtWidgets.QMainWindow()
    ui = Ui_firewoodApp()
    ui.setupUi(firewoodApp)
    firewoodApp.show()
    sys.exit(app.exec())
