# Form implementation generated from reading ui file 'mortalkombat.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

# Create a new class for Player.
class Player:
    # Create a method to create a new player.
    def __init__(self, name, speed, power, agility):
        # Set the object attributes for this class.
        self.player_name = name
        self.player_speed = speed
        self.player_power = power
        self.player_agility = agility
    
    # Create a method to modify the stats of a specific player.
    def modify_stats(self, speed, power, agility):
        self.player_speed = speed
        self.player_power = power
        self.player_agility = agility 

class Ui_mortalKombat(object):
    def setupUi(self, mortalKombat):
        mortalKombat.setObjectName("mortalKombat")
        mortalKombat.resize(1122, 855)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        mortalKombat.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=mortalKombat)
        self.centralwidget.setObjectName("centralwidget")
        self.tbPlayerCreation = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tbPlayerCreation.setGeometry(QtCore.QRect(20, 10, 1071, 771))
        self.tbPlayerCreation.setObjectName("tbPlayerCreation")
        self.tabCreatePlayer = QtWidgets.QWidget()
        self.tabCreatePlayer.setObjectName("tabCreatePlayer")
        self.lblName = QtWidgets.QLabel(parent=self.tabCreatePlayer)
        self.lblName.setGeometry(QtCore.QRect(170, 110, 131, 31))
        self.lblName.setObjectName("lblName")
        self.txtName = QtWidgets.QLineEdit(parent=self.tabCreatePlayer)
        self.txtName.setGeometry(QtCore.QRect(330, 120, 113, 22))
        self.txtName.setObjectName("txtName")
        self.lblSpeed = QtWidgets.QLabel(parent=self.tabCreatePlayer)
        self.lblSpeed.setGeometry(QtCore.QRect(170, 180, 131, 31))
        self.lblSpeed.setObjectName("lblSpeed")
        self.txtSpeed = QtWidgets.QLineEdit(parent=self.tabCreatePlayer)
        self.txtSpeed.setGeometry(QtCore.QRect(330, 190, 113, 22))
        self.txtSpeed.setObjectName("txtSpeed")
        self.lblPower = QtWidgets.QLabel(parent=self.tabCreatePlayer)
        self.lblPower.setGeometry(QtCore.QRect(170, 250, 131, 31))
        self.lblPower.setObjectName("lblPower")
        self.txtPower = QtWidgets.QLineEdit(parent=self.tabCreatePlayer)
        self.txtPower.setGeometry(QtCore.QRect(330, 260, 113, 22))
        self.txtPower.setObjectName("txtPower")
        self.lblAgility = QtWidgets.QLabel(parent=self.tabCreatePlayer)
        self.lblAgility.setGeometry(QtCore.QRect(170, 310, 131, 31))
        self.lblAgility.setObjectName("lblAgility")
        self.txtAgility = QtWidgets.QLineEdit(parent=self.tabCreatePlayer)
        self.txtAgility.setGeometry(QtCore.QRect(330, 320, 113, 22))
        self.txtAgility.setObjectName("txtAgility")
        self.btnCreatePlayer = QtWidgets.QPushButton(parent=self.tabCreatePlayer)
        self.btnCreatePlayer.setGeometry(QtCore.QRect(320, 400, 121, 28))
        self.btnCreatePlayer.setObjectName("btnCreatePlayer")
        self.tbPlayerCreation.addTab(self.tabCreatePlayer, "")
        self.tabModifyStats = QtWidgets.QWidget()
        self.tabModifyStats.setObjectName("tabModifyStats")
        self.lstCreatedPlayers = QtWidgets.QListWidget(parent=self.tabModifyStats)
        self.lstCreatedPlayers.setGeometry(QtCore.QRect(380, 60, 256, 192))
        self.lstCreatedPlayers.setObjectName("lstCreatedPlayers")
        self.lblCreatedPlayers = QtWidgets.QLabel(parent=self.tabModifyStats)
        self.lblCreatedPlayers.setGeometry(QtCore.QRect(454, 20, 131, 20))
        self.lblCreatedPlayers.setObjectName("lblCreatedPlayers")
        self.lblModifyName = QtWidgets.QLabel(parent=self.tabModifyStats)
        self.lblModifyName.setGeometry(QtCore.QRect(140, 370, 101, 16))
        self.lblModifyName.setObjectName("lblModifyName")
        self.txtPlayerName = QtWidgets.QLineEdit(parent=self.tabModifyStats)
        self.txtPlayerName.setGeometry(QtCore.QRect(140, 430, 113, 22))
        self.txtPlayerName.setReadOnly(True)
        self.txtPlayerName.setObjectName("txtPlayerName")
        self.lblModifySpeed = QtWidgets.QLabel(parent=self.tabModifyStats)
        self.lblModifySpeed.setGeometry(QtCore.QRect(340, 370, 101, 16))
        self.lblModifySpeed.setObjectName("lblModifySpeed")
        self.txtModifySpeed = QtWidgets.QLineEdit(parent=self.tabModifyStats)
        self.txtModifySpeed.setGeometry(QtCore.QRect(330, 430, 113, 22))
        self.txtModifySpeed.setReadOnly(False)
        self.txtModifySpeed.setObjectName("txtModifySpeed")
        self.lblModifyPower = QtWidgets.QLabel(parent=self.tabModifyStats)
        self.lblModifyPower.setGeometry(QtCore.QRect(540, 370, 101, 16))
        self.lblModifyPower.setObjectName("lblModifyPower")
        self.txtModifyPower = QtWidgets.QLineEdit(parent=self.tabModifyStats)
        self.txtModifyPower.setGeometry(QtCore.QRect(530, 430, 113, 22))
        self.txtModifyPower.setReadOnly(False)
        self.txtModifyPower.setObjectName("txtModifyPower")
        self.lblModifyAgility = QtWidgets.QLabel(parent=self.tabModifyStats)
        self.lblModifyAgility.setGeometry(QtCore.QRect(710, 370, 101, 16))
        self.lblModifyAgility.setObjectName("lblModifyAgility")
        self.txtModifyAgility = QtWidgets.QLineEdit(parent=self.tabModifyStats)
        self.txtModifyAgility.setGeometry(QtCore.QRect(700, 430, 113, 22))
        self.txtModifyAgility.setReadOnly(False)
        self.txtModifyAgility.setObjectName("txtModifyAgility")
        self.btnModifyStats = QtWidgets.QPushButton(parent=self.tabModifyStats)
        self.btnModifyStats.setGeometry(QtCore.QRect(440, 550, 93, 28))
        self.btnModifyStats.setObjectName("btnModifyStats")
        self.tbPlayerCreation.addTab(self.tabModifyStats, "")
        mortalKombat.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=mortalKombat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1122, 26))
        self.menubar.setObjectName("menubar")
        mortalKombat.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=mortalKombat)
        self.statusbar.setObjectName("statusbar")
        mortalKombat.setStatusBar(self.statusbar)

        self.retranslateUi(mortalKombat)
        self.tbPlayerCreation.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mortalKombat)
        # Create an empty dictionary to store player objects when created
        self.created_players = {}
        # Define the function that is executed when the Create Player button is clicked.
        self.btnCreatePlayer.clicked.connect(self.create_player)
        # Define the function that is executed when clicking on the Modify Stats tab.
        self.lstCreatedPlayers.itemClicked.connect(self.display_stats)
        # Define the function that is executed when the Modify Stats button is clicked.
        self.btnModifyStats.clicked.connect(self.modify_stats)

    def retranslateUi(self, mortalKombat):
        _translate = QtCore.QCoreApplication.translate
        mortalKombat.setWindowTitle(_translate("mortalKombat", "Mortal Kombat"))
        self.lblName.setText(_translate("mortalKombat", "Enter Player Name"))
        self.lblSpeed.setText(_translate("mortalKombat", "Enter Player Speed"))
        self.lblPower.setText(_translate("mortalKombat", "Enter Player Power"))
        self.lblAgility.setText(_translate("mortalKombat", "Enter Player Agility"))
        self.btnCreatePlayer.setText(_translate("mortalKombat", "Create Player"))
        self.tbPlayerCreation.setTabText(self.tbPlayerCreation.indexOf(self.tabCreatePlayer), _translate("mortalKombat", "Create Player"))
        self.lblCreatedPlayers.setText(_translate("mortalKombat", "Players Created"))
        self.lblModifyName.setText(_translate("mortalKombat", "Player Name"))
        self.lblModifySpeed.setText(_translate("mortalKombat", "Player Speed"))
        self.lblModifyPower.setText(_translate("mortalKombat", "Player Power"))
        self.lblModifyAgility.setText(_translate("mortalKombat", "Player Agility"))
        self.btnModifyStats.setText(_translate("mortalKombat", "Modify Stats"))
        self.tbPlayerCreation.setTabText(self.tbPlayerCreation.indexOf(self.tabModifyStats), _translate("mortalKombat", "Modify Stats"))

    # Define the create_player function to add a new player and corresponding stats to the dictionary.
    def create_player(self):
        try:
            
            # Get the player's Name and store it in the Name variable.
            name = self.txtName.text()
            # Get the player's Speed and store it in the Speed variable.
            speed = self.txtSpeed.text()
            # Get the player's Power and store it in the Power variable.
            power = self.txtPower.text()
            # Get the player's Agility and store it in the Agility variable.
            agility = self.txtAgility.text()
            
            # Validate the user has entered the Name as letters and entered the Speed, Power, and Agility as numbers.
            if(name.isalpha() and speed.isdigit() and power.isdigit() and agility.isdigit()):
                            
                # Use the Player class to create the new player object.
                player_object = Player(name, speed, power, agility)
                # The dictionary will have player name as the key and player object as the value
                self.created_players[name] = player_object
                # Display the the name of the player created to the List Box on the Modify Stats tab.
                self.lstCreatedPlayers.addItem(name)

                # Display a message box: Player Created
                # Display a message to indicate the player was successfully added to the dictionary.
                msg = QtWidgets.QMessageBox()
                # set the title of the message box to Student Grade
                msg.setWindowTitle("Mortal Kombat")
                # set the display text of the message box
                msg.setText("Player created.")
                # Execute the message box
                msg.exec()
                
            else:
                # Display an error message to the user if the Name, Speed, Power, or Agility are not entered correctly.
                msg = QtWidgets.QMessageBox()
                # Set the title of the Message Box to Mortal Kombat.
                msg.setWindowTitle("Mortal Kombat")
                # Set the display text of the Message Box.
                msg.setText("Please enter valid inputs for the Player Name, Speed, Power, and Agility")
                # Execute the Message Box.
                msg.exec()    
        
        # Generic exception block for all other unexpected errors.
        except Exception as e:
            print(e)
    
    # Define the display_stats function to display the stats for a player on the Modify Stats tab.
    def display_stats(self, item):
        try:
            # Get the name of the currently selected player in the list widget
            selected_player = item.text()
            # Retrieve the player object from the dictionary of all previously created players.
            player_object = self.created_players.get(selected_player)
            # Display the Player Name in the Player Name text box.
            self.txtPlayerName.setText(player_object.player_name)
            # Display the Player Speed in the Player Speed text box.
            self.txtModifySpeed.setText(player_object.player_speed)
            # Display the Player Power in the Player Power text box.
            self.txtModifyPower.setText(player_object.player_power)
            # Display the Player Agility in the Player Agility text box.
            self.txtModifyAgility.setText(player_object.player_agility)
            
        # Generic exception block for all other unexpected errors.
        except Exception as e:
            print(e)

    # Define the modify_stats method to modify the player stats
    def modify_stats(self):
        try:
            # Get the Name and store it in the name variable.
            name = self.txtPlayerName.text()
            # Get the Speed and store it in the speed variable.
            speed = self.txtModifySpeed.text()
            # Get the Power and store it in the power variable.
            power = self.txtModifyPower.text()
            # Get the Agility and store it in the agility variable.
            agility = self.txtModifyAgility.text()
            # Retrieve the player object from the dictionary.
            player_object = self.created_players.get(name)
            # Call the modify_stats method of the Player object.
            player_object.modify_stats(speed,power,agility)
            # Store the modified object to the dictionary.
            self.created_players[name] = player_object

        # Generic exception block for all other unexpected errors.
        except Exception as e:
            print(e)            


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mortalKombat = QtWidgets.QMainWindow()
    ui = Ui_mortalKombat()
    ui.setupUi(mortalKombat)
    mortalKombat.show()
    sys.exit(app.exec())
