# Form implementation generated from reading ui file 'financialplanner.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_financialPlanner(object):
    def setupUi(self, financialPlanner):
        financialPlanner.setObjectName("financialPlanner")
        financialPlanner.resize(1102, 837)
        self.centralwidget = QtWidgets.QWidget(parent=financialPlanner)
        self.centralwidget.setObjectName("centralwidget")
        self.txtAnnualAmount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtAnnualAmount.setGeometry(QtCore.QRect(600, 260, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtAnnualAmount.setFont(font)
        self.txtAnnualAmount.setObjectName("txtAnnualAmount")
        self.lblAnnualAmount = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAnnualAmount.setGeometry(QtCore.QRect(360, 240, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblAnnualAmount.setFont(font)
        self.lblAnnualAmount.setObjectName("lblAnnualAmount")
        self.lblTargetAmount = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTargetAmount.setGeometry(QtCore.QRect(360, 360, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblTargetAmount.setFont(font)
        self.lblTargetAmount.setObjectName("lblTargetAmount")
        self.txtTargetAmount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTargetAmount.setGeometry(QtCore.QRect(600, 380, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtTargetAmount.setFont(font)
        self.txtTargetAmount.setObjectName("txtTargetAmount")
        self.lblPlan = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPlan.setGeometry(QtCore.QRect(350, 460, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblPlan.setFont(font)
        self.lblPlan.setObjectName("lblPlan")
        self.cmbPlan = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbPlan.setGeometry(QtCore.QRect(602, 480, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.cmbPlan.setFont(font)
        self.cmbPlan.setObjectName("cmbPlan")
        self.cmbPlan.addItem("")
        self.cmbPlan.addItem("")
        self.cmbPlan.addItem("")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(600, 560, 111, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnCalculate.setFont(font)
        self.btnCalculate.setObjectName("btnCalculate")
        self.lblResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(350, 630, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblResult.setFont(font)
        self.lblResult.setObjectName("lblResult")
        self.txtResult = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtResult.setGeometry(QtCore.QRect(600, 650, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtResult.setFont(font)
        self.txtResult.setObjectName("txtResult")
        financialPlanner.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=financialPlanner)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1102, 26))
        self.menubar.setObjectName("menubar")
        financialPlanner.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=financialPlanner)
        self.statusbar.setObjectName("statusbar")
        financialPlanner.setStatusBar(self.statusbar)

        self.retranslateUi(financialPlanner)
        QtCore.QMetaObject.connectSlotsByName(financialPlanner)
        # When the Calculate button is clicked, execute the calculate_time_taken function.
        self.btnCalculate.clicked.connect(self.calculate_time_taken)

    def retranslateUi(self, financialPlanner):
        _translate = QtCore.QCoreApplication.translate
        financialPlanner.setWindowTitle(_translate("financialPlanner", "Financial Planner"))
        self.lblAnnualAmount.setText(_translate("financialPlanner", "Enter Annual Amount"))
        self.lblTargetAmount.setText(_translate("financialPlanner", "Enter Target Amount"))
        self.lblPlan.setText(_translate("financialPlanner", "Select Retirement Plan"))
        self.cmbPlan.setItemText(0, _translate("financialPlanner", "Plan 2040"))
        self.cmbPlan.setItemText(1, _translate("financialPlanner", "Plan 2050"))
        self.cmbPlan.setItemText(2, _translate("financialPlanner", "Plan 2060"))
        self.btnCalculate.setText(_translate("financialPlanner", "Calculate"))
        self.lblResult.setText(_translate("financialPlanner", "Time Taken"))
    
    # Define the calculate_time_taken function to accept the user inputs and calculate the number of years it takes for the portfolio to reach the target amount.
    def calculate_time_taken(self):
        # Get user input value from Annual Amount text box
        annual_amount = int(self.txtAnnualAmount.text())
        # Get user input value from Target Amount text box
        target_amount = int(self.txtTargetAmount.text())
        # Get the users current selected plan
        plan_selection = self.cmbPlan.currentText()
        
        years = 0
        # current portfolio value
        current_amount = 0
        
        # Get the user's financial plan selection.
        if(plan_selection == "Plan 2040"):
            rate = 7.0
        elif(plan_selection == "Plan 2050"):
            rate = 6.0
        else:
            rate = 5.0
        
        # Use a while loop to calculate the number of years it will take for the portfolio to reach the target amount based on the plan selection.
        while(current_amount < target_amount):
            current_amount = (current_amount + annual_amount) * (1 + rate/100)
            years = years + 1
            
        self.txtResult.setText(str(years))   
            
            
            
        
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    financialPlanner = QtWidgets.QMainWindow()
    ui = Ui_financialPlanner()
    ui.setupUi(financialPlanner)
    financialPlanner.show()
    sys.exit(app.exec())
