# Form implementation generated from reading ui file 'carfinancing.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_carFinancing(object):
    def setupUi(self, carFinancing):
        carFinancing.setObjectName("carFinancing")
        carFinancing.resize(1109, 846)
        self.centralwidget = QtWidgets.QWidget(parent=carFinancing)
        self.centralwidget.setObjectName("centralwidget")
        self.tbCarFinancing = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tbCarFinancing.setGeometry(QtCore.QRect(10, 10, 1081, 771))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.tbCarFinancing.setFont(font)
        self.tbCarFinancing.setObjectName("tbCarFinancing")
        self.tabCarPurchase = QtWidgets.QWidget()
        self.tabCarPurchase.setObjectName("tabCarPurchase")
        self.lblName = QtWidgets.QLabel(parent=self.tabCarPurchase)
        self.lblName.setGeometry(QtCore.QRect(80, 20, 81, 41))
        self.lblName.setObjectName("lblName")
        self.lblAge = QtWidgets.QLabel(parent=self.tabCarPurchase)
        self.lblAge.setGeometry(QtCore.QRect(80, 60, 81, 41))
        self.lblAge.setObjectName("lblAge")
        self.txtName = QtWidgets.QLineEdit(parent=self.tabCarPurchase)
        self.txtName.setGeometry(QtCore.QRect(270, 30, 131, 22))
        self.txtName.setObjectName("txtName")
        self.txtAge = QtWidgets.QLineEdit(parent=self.tabCarPurchase)
        self.txtAge.setGeometry(QtCore.QRect(270, 70, 131, 22))
        self.txtAge.setObjectName("txtAge")
        self.cmbSelection = QtWidgets.QComboBox(parent=self.tabCarPurchase)
        self.cmbSelection.setGeometry(QtCore.QRect(270, 110, 131, 22))
        self.cmbSelection.setObjectName("cmbSelection")
        self.cmbSelection.addItem("")
        self.cmbSelection.addItem("")
        self.cmbSelection.addItem("")
        self.cmbSelection.addItem("")
        self.lblSelection = QtWidgets.QLabel(parent=self.tabCarPurchase)
        self.lblSelection.setGeometry(QtCore.QRect(80, 100, 111, 41))
        self.lblSelection.setObjectName("lblSelection")
        self.grpSelectModel = QtWidgets.QGroupBox(parent=self.tabCarPurchase)
        self.grpSelectModel.setGeometry(QtCore.QRect(460, 90, 231, 61))
        self.grpSelectModel.setObjectName("grpSelectModel")
        self.rdBasic = QtWidgets.QRadioButton(parent=self.grpSelectModel)
        self.rdBasic.setGeometry(QtCore.QRect(10, 20, 121, 20))
        self.rdBasic.setObjectName("rdBasic")
        self.rdHybrid = QtWidgets.QRadioButton(parent=self.grpSelectModel)
        self.rdHybrid.setGeometry(QtCore.QRect(80, 20, 121, 20))
        self.rdHybrid.setObjectName("rdHybrid")
        self.rdSport = QtWidgets.QRadioButton(parent=self.grpSelectModel)
        self.rdSport.setGeometry(QtCore.QRect(160, 20, 121, 20))
        self.rdSport.setObjectName("rdSport")
        self.lblDownPayment = QtWidgets.QLabel(parent=self.tabCarPurchase)
        self.lblDownPayment.setGeometry(QtCore.QRect(80, 140, 141, 41))
        self.lblDownPayment.setObjectName("lblDownPayment")
        self.txtDownPayment = QtWidgets.QLineEdit(parent=self.tabCarPurchase)
        self.txtDownPayment.setGeometry(QtCore.QRect(270, 150, 131, 22))
        self.txtDownPayment.setObjectName("txtDownPayment")
        self.lstPayments = QtWidgets.QListWidget(parent=self.tabCarPurchase)
        self.lstPayments.setGeometry(QtCore.QRect(350, 240, 701, 491))
        self.lstPayments.setObjectName("lstPayments")
        self.btnPurchase = QtWidgets.QPushButton(parent=self.tabCarPurchase)
        self.btnPurchase.setGeometry(QtCore.QRect(80, 200, 93, 28))
        self.btnPurchase.setObjectName("btnPurchase")
        self.btnClear = QtWidgets.QPushButton(parent=self.tabCarPurchase)
        self.btnClear.setGeometry(QtCore.QRect(80, 240, 93, 28))
        self.btnClear.setObjectName("btnClear")
        self.btnExit = QtWidgets.QPushButton(parent=self.tabCarPurchase)
        self.btnExit.setGeometry(QtCore.QRect(200, 240, 93, 28))
        self.btnExit.setObjectName("btnExit")
        self.btnPayments = QtWidgets.QPushButton(parent=self.tabCarPurchase)
        self.btnPayments.setGeometry(QtCore.QRect(200, 200, 111, 28))
        self.btnPayments.setObjectName("btnPayments")
        self.lblMonthlyPayments = QtWidgets.QLabel(parent=self.tabCarPurchase)
        self.lblMonthlyPayments.setGeometry(QtCore.QRect(650, 190, 121, 41))
        self.lblMonthlyPayments.setObjectName("lblMonthlyPayments")
        self.tbCarFinancing.addTab(self.tabCarPurchase, "")
        self.tabPurchasesMade = QtWidgets.QWidget()
        self.tabPurchasesMade.setObjectName("tabPurchasesMade")
        self.lstPurchasesMade = QtWidgets.QListWidget(parent=self.tabPurchasesMade)
        self.lstPurchasesMade.setGeometry(QtCore.QRect(0, 70, 1071, 331))
        self.lstPurchasesMade.setObjectName("lstPurchasesMade")
        self.lblPurchasesMade = QtWidgets.QLabel(parent=self.tabPurchasesMade)
        self.lblPurchasesMade.setGeometry(QtCore.QRect(450, 20, 121, 41))
        self.lblPurchasesMade.setObjectName("lblPurchasesMade")
        self.tbCarFinancing.addTab(self.tabPurchasesMade, "")
        carFinancing.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=carFinancing)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1109, 26))
        self.menubar.setObjectName("menubar")
        carFinancing.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=carFinancing)
        self.statusbar.setObjectName("statusbar")
        carFinancing.setStatusBar(self.statusbar)

        self.retranslateUi(carFinancing)
        self.tbCarFinancing.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(carFinancing)
        
        # Create a new dictionary called price_dictionary that will be populated using the load_data function.
        self.price_dictionary = self.load_data("carprice.txt")
        # Define the function that is executed when clicking the Purchase, Show Payments, Exit, and Clear buttons.
        self.btnPayments.clicked.connect(self.show_payments)
        self.btnPurchase.clicked.connect(self.purchase_made)
        self.btnClear.clicked.connect(self.clear)
        self.btnExit.clicked.connect(self.exit_application)
        # Define the function that is executed when clicking on the Purchases Made tab.
        self.tbCarFinancing.currentChanged.connect(self.display_data)

    def retranslateUi(self, carFinancing):
        _translate = QtCore.QCoreApplication.translate
        carFinancing.setWindowTitle(_translate("carFinancing", "Car Financing"))
        self.lblName.setText(_translate("carFinancing", "Enter Name"))
        self.lblAge.setText(_translate("carFinancing", "Enter Age"))
        self.cmbSelection.setItemText(0, _translate("carFinancing", "Sonata"))
        self.cmbSelection.setItemText(1, _translate("carFinancing", "Corolla"))
        self.cmbSelection.setItemText(2, _translate("carFinancing", "Civic"))
        self.cmbSelection.setItemText(3, _translate("carFinancing", "Camry"))
        self.lblSelection.setText(_translate("carFinancing", "Select Car Type"))
        self.grpSelectModel.setTitle(_translate("carFinancing", "Select Model"))
        self.rdBasic.setText(_translate("carFinancing", "Basic"))
        self.rdHybrid.setText(_translate("carFinancing", "Hybrid"))
        self.rdSport.setText(_translate("carFinancing", "Sport"))
        self.lblDownPayment.setText(_translate("carFinancing", "Enter Down Payment"))
        self.btnPurchase.setText(_translate("carFinancing", "Purchase"))
        self.btnClear.setText(_translate("carFinancing", "Clear"))
        self.btnExit.setText(_translate("carFinancing", "Exit"))
        self.btnPayments.setText(_translate("carFinancing", "Show Payments"))
        self.lblMonthlyPayments.setText(_translate("carFinancing", "Monthly Payments"))
        self.tbCarFinancing.setTabText(self.tbCarFinancing.indexOf(self.tabCarPurchase), _translate("carFinancing", "Car Purchase"))
        self.lblPurchasesMade.setText(_translate("carFinancing", "Purchases Made"))
        self.tbCarFinancing.setTabText(self.tbCarFinancing.indexOf(self.tabPurchasesMade), _translate("carFinancing", "Purchases Made"))
    
    # Define the load_data function to read each line of the carprice.txt file and load into a dictionary called price.
    def load_data(self, file_name):
        try:
            # Create an empty dictionary called price.
            price = {}
            # Read each line of the carprice.txt file.
            with open(file_name, "r") as fname:
                for line in fname:
                    # strip() will remove extra whitespaces before and after the text.
                    # split() will split the data based on the delimiter of ",".
                    car_type, car_price = line.strip().split(",")
                    # Add a new key value pair to the dictionary.
                    price[car_type] = int(car_price)
            return price
            
        # Specific exception block to handle file not found error
        except FileNotFoundError:
            print("The file does not exist")
        # Generic exception block for all other unexpected errors
        except Exception as e:
            print(e)
    
    # Define the purchases_made function to accept all user inputs and the write the data to an external file called purchases_made.txt.
    def purchase_made(self):
        try:
            # Get the customer's Name and store it in the name variable.
            name = self.txtName.text()
            # Get the customer's Age and store it in the age variable.
            age = self.txtAge.text()
            # Get the customer's Down Payment and store it in the down_payment variable.
            down_payment = self.txtDownPayment.text()
            # Get the customer's Car Selection and store it in the current_selection variable.
            current_selection = self.cmbSelection.currentText()
            
            # Get the customer's Choice of Model and store it in the model variable.
            # If the Basic radio button is selected, set the model variable to Basic.
            if(self.rdBasic.isChecked()):
                model = "Basic"
            # If the Hybrid radio button is selected, set the model variable to Hybrid.
            elif(self.rdHybrid.isChecked()):
                model = "Hybrid"
            # If the Sport radio button is selected, set the model variable to Sport.
            elif(self.rdSport.isChecked()):
                model = "Sport"
            # If a radio button is not selected, set the model variable to Not Selected.
            else:
                model = "Not Selected" 
            
            # Validate the user has entered the Name as letters, has entered the Age and Down Payment as numbers, and selected a Model Choice.
            if(name.isalpha() and age.isdigit() and down_payment.isdigit() and model != "Not Selected"):
                
                # Write the user inputs to a new line in the purchases_made.txt file.
                with open("purchases_made.txt", "a") as fname:
                    fname.write(name+",  "+age+",  "+current_selection+",  "+model+",  "+down_payment+"\n")
            
            else:
                # Display an error message to the user if the Name, Age, Down Payment, or model choice is not filled in.
                msg = QtWidgets.QMessageBox()
                # Set the title of the Message Box to Car Financing.
                msg.setWindowTitle("Car Financing")
                # Set the display text of the Message Box.
                msg.setText("Please enter valid inputs for the Name, Age, and Down Payment and select a Model Choice.")
                # Execute the Message Box
                msg.exec()
            
        # Generic exception block for all other unexpected errors 
        except Exception as e:
            print(e)
    
    # Define the show_payments function to calculate the monthly payments and display the data in a list box on the Car Purchase tab.
    def show_payments(self):
        try:
            # Define the total_price variable and set it to 0.
            total_price = 0
            # Define the loan_amount variable and set it to 0.
            loan_amount = 0
            # Define the annual_rate variable and set it to 0.06.
            annual_rate = 0.06
            # Define and calculate and the monthly_rate variable.
            monthly_rate = annual_rate/12
            # Define the loan_term variable and set it to 60 months.
            loan_term = 60
            # Define the loan_term_months variable and set it to 0.
            loan_term_months = 1
            # Define the monthly_payment variable and set it to 0.
            monthly_payment = 0
            # Get the customer's Car Selection and store it in the current_selection variable.
            current_selection = self.cmbSelection.currentText()
            # Get the customer's Down Payment and store it in the down_payment variable.
            down_payment = self.txtDownPayment.text()
            
            # Get the price of the car from the price dictionary based on the current_selection variable.
            total_price = self.price_dictionary.get(current_selection)
            
            # Get the customer's Choice of Model and store it in the model variable.
            # If the Basic radio button is selected, set the model variable to Basic.
            if(self.rdBasic.isChecked()):
                model = "Basic"
            # If the Hybrid radio button is selected, set the model variable to Hybrid.
            elif(self.rdHybrid.isChecked()):
                model = "Hybrid"
            # If the Sport radio button is selected, set the model variable to Sport.
            elif(self.rdSport.isChecked()):
                model = "Sport"
            # If a radio button is not selected, set the model variable to Not Selected.
            else:
                model = "Not Selected" 
                
            # Validate the user has entered the Down Payment as a number and selected a Model Choice.
            if(down_payment.isdigit() and model != "Not Selected"):
                
                # Calculate the total_price variable based on the customer's Choice of Model.
                # If the Hybrid radio button is checked, add 20% to the car price from the price dictionary.
                if(self.rdHybrid.isChecked()):
                    total_price = total_price * 1.20
                # If the Sport radio button is checked, add 30% to the car price from the price dictionary.
                elif(self.rdSport.isChecked()):
                    total_price = total_price * 1.30
                # If the Basic radio button or no button is checked, make no changes to the total_price variable.
                else:
                    total_price = total_price + 0
            
                # Convert the down_payment variable from text to an integer value.
                down_payment = int(down_payment)
                # Calculate the loan_amount variable by subtracting the down_payment from the loan_amount.
                loan_amount = total_price - down_payment
                # Calculate the monthly_payment.
                monthly_payment = (loan_amount * monthly_rate * ((1 + monthly_rate) ** loan_term)) / ((1 + monthly_rate) ** loan_term - 1)
                # Create the currency_payment variable as a formatted version of the monthly_payment variable.
                currency_payment = f"${monthly_payment:,.2f}"
            
                # Write column headings to the Monthly Payments list box on the Car Purchase tab.
                self.lstPayments.addItem("Month          Payment          Remaining Balance")
            
                # For each month leading up to the loan_term, calculate and display the monthly payments in the list box on the Car Purchase tab.
                for each_month in range(1, loan_term + 1):
                    # Update the loan_amount to represent the remaining loan balance by subtracting the portion of the monthly payment that is for principal.
                    loan_amount = loan_amount - (monthly_payment - (loan_amount * monthly_rate))
                    # Create the currency_balance variable as a formatted version of the loan_amount variable.
                    currency_balance = f"${loan_amount:,.2f}"
                    # Write the month number, monthly payment, and remaining loan balance to the list box on the Card Purchase tab.
                    self.lstPayments.addItem(str(loan_term_months)+"               "+currency_payment+"               "+currency_balance)
                    # Increment the loan_term_months variable by 1 month.
                    loan_term_months = loan_term_months + 1
                    # Break statement to exit the loop if the loan_amount < 0.
                    if(loan_amount < 0):
                        break
            
            else:
                # Display an error message to the user if the Down Payment or Model Choice is not filled in.
                msg = QtWidgets.QMessageBox()
                # Set the title of the Message Box to Car Financing.
                msg.setWindowTitle("Car Financing")
                # Set the display text of the Message Box.
                msg.setText("Please enter valid inputs for the Down Payment and select a Model Choice.")
                # Execute the Message Box
                msg.exec()
            
        # Generic exception block for all other unexpected errors        
        except Exception as e:
            print(e)
                        
    # Define the clear function that resets all fields to their default values when the Clear button is clicked.
    def clear(self):
        try:
            # Clears the Name text box.
            self.txtName.clear()
            # Clears the Age text box.
            self.txtAge.clear()
            # Re-set the Car Selection combo box to Sonata.
            self.cmbSelection.setCurrentIndex(0)
            # Re-set the Model Type radio button to Basic.
            self.rdBasic.setChecked(True)
            # Clears the Down Payment text box.
            self.txtDownPayment.clear()
            # Clear the Show Payments list box.
            self.lstPayments.clear()
        
        # Generic exception block for all other unexpected errors
        except Exception as e:
            print(e)
            
    # Define the exit_application function that closes the application when the Exit button is clicked.
    def exit_application(self):
        try:
            #Close the application when the Exit button is clicked.
            QtWidgets.QApplication.quit()  
        
        # Generic exception block for all other unexpected errors
        except Exception as e:
            print(e)
    
    # Define the display_data function to read the data from the purchases_made.txt file and display
    # each line in the list box on the Purchases Made tab.
    def display_data(self, index):
        try:
            # Clear the data on the Purchases Made tab if user clicks on the Car Purchase tab.
            if(index == 0):
                self.lstPurchasesMade.clear()
            # Read each line of the purchases_made.txt file and display each line in the list box on the
            # Purchases Made tab.
            else:                
                with open("purchases_made.txt", "r") as fname:
                    for line in fname:
                        self.lstPurchasesMade.addItem(line)
        
        # Specific exception block to handle file not found error
        except FileNotFoundError:
            print("No purchase data exists")
        
        # Generic exception block for all other unexpected errors
        except Exception as e:
            print(e) 
            
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    carFinancing = QtWidgets.QMainWindow()
    ui = Ui_carFinancing()
    ui.setupUi(carFinancing)
    carFinancing.show()
    sys.exit(app.exec())
