# Form implementation generated from reading ui file 'financialplannertwo.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_financialPlanner(object):
    def setupUi(self, financialPlanner):
        financialPlanner.setObjectName("financialPlanner")
        financialPlanner.resize(1114, 858)
        self.centralwidget = QtWidgets.QWidget(parent=financialPlanner)
        self.centralwidget.setObjectName("centralwidget")
        self.lblAnnualAmount = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAnnualAmount.setGeometry(QtCore.QRect(260, 150, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblAnnualAmount.setFont(font)
        self.lblAnnualAmount.setObjectName("lblAnnualAmount")
        self.txtAnnualAmount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtAnnualAmount.setGeometry(QtCore.QRect(530, 160, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtAnnualAmount.setFont(font)
        self.txtAnnualAmount.setObjectName("txtAnnualAmount")
        self.lblTotalTime = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTotalTime.setGeometry(QtCore.QRect(260, 220, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblTotalTime.setFont(font)
        self.lblTotalTime.setObjectName("lblTotalTime")
        self.txtTotalTime = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTotalTime.setGeometry(QtCore.QRect(530, 240, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtTotalTime.setFont(font)
        self.txtTotalTime.setObjectName("txtTotalTime")
        self.lstOutput = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lstOutput.setGeometry(QtCore.QRect(750, 310, 281, 321))
        self.lstOutput.setObjectName("lstOutput")
        self.lblOutput = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblOutput.setGeometry(QtCore.QRect(840, 260, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblOutput.setFont(font)
        self.lblOutput.setObjectName("lblOutput")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(540, 400, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnCalculate.setFont(font)
        self.btnCalculate.setObjectName("btnCalculate")
        self.chkPlan = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.chkPlan.setGeometry(QtCore.QRect(540, 300, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.chkPlan.setFont(font)
        self.chkPlan.setObjectName("chkPlan")
        self.btnClear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(370, 600, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.btnExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(620, 600, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnExit.setFont(font)
        self.btnExit.setObjectName("btnExit")
        financialPlanner.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=financialPlanner)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1114, 26))
        self.menubar.setObjectName("menubar")
        financialPlanner.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=financialPlanner)
        self.statusbar.setObjectName("statusbar")
        financialPlanner.setStatusBar(self.statusbar)

        self.retranslateUi(financialPlanner)
        QtCore.QMetaObject.connectSlotsByName(financialPlanner)
        # Define the function that is executed when clicking the Calculate, Clear, and Exit buttons.
        self.btnCalculate.clicked.connect(self.calculate)
        self.btnClear.clicked.connect(self.clear)
        self.btnExit.clicked.connect(self.exit_application)

    def retranslateUi(self, financialPlanner):
        _translate = QtCore.QCoreApplication.translate
        financialPlanner.setWindowTitle(_translate("financialPlanner", "Financial Planner"))
        self.lblAnnualAmount.setText(_translate("financialPlanner", "Enter Annual Amount"))
        self.lblTotalTime.setText(_translate("financialPlanner", "Enter Total Time"))
        self.lblOutput.setText(_translate("financialPlanner", "Portfolio Value"))
        self.btnCalculate.setText(_translate("financialPlanner", "Calculate"))
        self.chkPlan.setText(_translate("financialPlanner", "Plan 2040"))
        self.btnClear.setText(_translate("financialPlanner", "Clear"))
        self.btnExit.setText(_translate("financialPlanner", "Exit"))
        
    # Define the calculate function to display the year and the current portfolio value in a list box until the end of the investment plan.    
    def calculate(self):
        # Get the annual amount entered by the user and store it in the annual_amount variable.
        annual_amount = self.txtAnnualAmount.text()
        # Get the total time entered by the user and store it in the total_time variable.
        total_time = self.txtTotalTime.text()
        # Define the current_portfolio_value variable and set it to 0.
        current_portfolio_value = 0
        # Define the years variable and set it to 0.
        years = 0
        
        # Validate that the user has entered the Annual Amount and Total Time as numbers.
        if(annual_amount.isdigit() and total_time.isdigit()):
            # Convert the annual_amount variable to an integer.
            annual_amount = int(annual_amount)
            # Convert the total_time variable to an integer.
            total_time = int(total_time)
            
            # Determine what rate to use based on whether the option to use a risky investment plan is used.
            if(self.chkPlan.isChecked):
                rate = 7.0
            else:
                rate = 5.0
            
            # Write column headings to the list box.
            self.lstOutput.addItem("Year" + "   " + "Current Portfolio Value")    
            
            # For each year, display the year and the current portfolio value in the list box.
            for each_year in range(0, total_time):
                current_portfolio_value = (current_portfolio_value + annual_amount) * (1 + rate/100)
                years = years + 1
                currency = f"${current_portfolio_value:,.2f}"
                self.lstOutput.addItem(str(years)+ "    " + currency)
        
        # Display an error message to the user if the Annual Amount and Total Time is not entereed as numbers.
        else:
            msg = QtWidgets.QMessageBox()
            msg.setWindowTitle("Financial Planner")
            msg.setText("Please enter valid inputs for annual amount and time taken")
            msg.exec()
            
    # Define the clear function that resets all fields to their default values when the Clear button is clicked.        
    def clear(self):
        # Will clear the Annual Amount text box
        self.txtAnnualAmount.clear()
        # Will clear the Total Time text box
        self.txtTotalTime.clear()
        # Will un-check the checkbox
        self.chkPlan.setChecked(False)
        # Will clear the list box
        self.lstOutput.clear()
    
    # Define the exit function that closes the application when the Exit button is clicked.
    def exit_application(self):
        QtWidgets.QApplication.quit()        
            
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    financialPlanner = QtWidgets.QMainWindow()
    ui = Ui_financialPlanner()
    ui.setupUi(financialPlanner)
    financialPlanner.show()
    sys.exit(app.exec())
